<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/includes/bootstrap.php';
require_permission('hunts.manage');
$pdo=db();
if(is_post()){
    verify_csrf();
    try{
        $action=(string)input('action'); $id=(int)input('id');
        if($action==='delete'){$pdo->prepare('DELETE FROM riddle_pool WHERE riddle_id=?')->execute([$id]);audit_log((int)admin()['id'],'QUESTION_DELETED','riddle_pool',(string)$id);flash('success','Question deleted.');}
        else { $spot=trim((string)input('spot_id'));$text=trim((string)input('riddle_text'));$instructions=trim((string)input('instruction_text'));$answer=trim((string)input('primary_answer'));$mode=strtoupper((string)input('question_mode','SINGLE'));$time=max(5,min(3600,(int)input('answer_time_seconds',60)));if($spot===''||$text===''||$answer===''||!in_array($mode,['SINGLE','MULTIPLE'],true))throw new InvalidArgumentException('Spot, question and primary answer are required.');$syn=array_values(array_filter(array_map('trim',explode(',',(string)input('synonyms')))));$params=[$mode,$text,$instructions?:null,$answer,safe_json($syn),trim((string)input('yt_video_id'))?:null,trim((string)input('channel_url'))?:null,$time];if($action==='edit'){$params[]=$id;$pdo->prepare('UPDATE riddle_pool SET question_mode=?,riddle_text=?,instruction_text=?,primary_answer=?,synonyms=?,yt_video_id=?,channel_url=?,answer_time_seconds=? WHERE riddle_id=?')->execute($params);audit_log((int)admin()['id'],'QUESTION_UPDATED','riddle_pool',(string)$id);}else{$pdo->prepare('INSERT INTO riddle_pool(spot_id,question_mode,riddle_text,instruction_text,primary_answer,synonyms,yt_video_id,channel_url,answer_time_seconds,status) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute([$spot,$mode,$text,$instructions?:null,$answer,safe_json($syn),trim((string)input('yt_video_id'))?:null,trim((string)input('channel_url'))?:null,$time,strtoupper((string)input('status','ACTIVE'))]);audit_log((int)admin()['id'],'QUESTION_CREATED','riddle_pool',(string)$pdo->lastInsertId());}flash('success','Question saved.');}
    }catch(Throwable $e){flash('error',$e->getMessage());}
    redirect('/admin/hunts/questions.php');
}
$spots=$pdo->query('SELECT spot_id,spot_name FROM spot_campaigns ORDER BY spot_name')->fetchAll();
$rows=$pdo->query('SELECT r.*,s.spot_name FROM riddle_pool r JOIN spot_campaigns s ON s.spot_id=r.spot_id ORDER BY r.riddle_id DESC')->fetchAll();
$pageTitle='Question Manager';$pageSubtitle='Create, edit, delete and bulk-manage dynamic riddle questions';require APP_ROOT.'/includes/header.php';
?>
<section class="panel"><div class="panel-head"><h2>Add question</h2><a class="btn secondary" href="../hunts/collections.php">Manage collections</a><a class="btn secondary" href="<?=e(app_url('/admin/qr/bulk.php'))?>">Bulk upload / manage (CSV)</a></div><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="field"><label>Master category campaign</label><select name="spot_id" required><option value="">Select campaign</option><?php foreach($spots as $s):?><option value="<?=e($s['spot_id'])?>"><?=e($s['spot_name'].' · '.$s['spot_id'])?></option><?php endforeach?></select></div><div class="field"><label>Question section</label><select name="question_mode"><option value="SINGLE">Single question</option><option value="MULTIPLE">Multiple questions</option></select></div><div class="field full"><label>Question / riddle text (Hindi / English)</label><textarea name="riddle_text" required></textarea></div><div class="field full"><label>Instructions for user (optional)</label><textarea name="instruction_text" placeholder="Read the clue and submit one answer within the time limit."></textarea></div><div class="field"><label>Primary answer</label><input name="primary_answer" required></div><div class="field"><label>Alternative synonyms (comma-separated)</label><input name="synonyms"></div><div class="field"><label>YouTube video ID</label><input name="yt_video_id"></div><div class="field"><label>Video channel URL</label><input type="url" name="channel_url"></div><div class="field"><label>Time to answer (seconds)</label><input type="number" name="answer_time_seconds" min="5" max="3600" value="60" required></div><div class="field"><label>Status</label><select name="status"><option>ACTIVE</option><option>INACTIVE</option></select></div><div class="field full actions"><button class="btn" type="submit">Add question</button><button class="btn secondary" type="button" id="load-question-sample">Load sample question</button></div></form></section>
<section class="panel"><h2>Questions</h2><div class="table-wrap"><table><thead><tr><th>Campaign</th><th>Question</th><th>Answer / synonyms</th><th>Video</th><th>Time</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['spot_name'])?><br><small><?=e($r['question_mode']??'SINGLE')?></small></td><td><?=e($r['riddle_text'])?><br><small><?=e($r['instruction_text']??'')?></small></td><td><?=e($r['primary_answer'])?><br><small><?=e(implode(', ',json_decode((string)$r['synonyms'],true)?:[]))?></small></td><td><?=e($r['yt_video_id']??'—')?></td><td><?=e($r['answer_time_seconds']??60)?> sec</td><td><form method="post" data-confirm="Delete this question?" class="actions"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=e($r['riddle_id'])?>"><button class="btn danger small">Delete</button></form></td></tr><?php endforeach?></tbody></table><?php if(!$rows):?><div class="empty">No questions created yet.</div><?php endif?></div></section><?php require APP_ROOT.'/includes/footer.php';
