<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit("CLI only\n");
$_SERVER['REQUEST_URI']='/tests/bonus_qr_integration.php';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Bonus QR integration test';
require dirname(__DIR__).'/includes/bootstrap.php';
function assert_ok(bool $ok,string $message): void {if(!$ok)throw new RuntimeException($message);}
$pdo=db();$admin=(int)$pdo->query('SELECT id FROM admins ORDER BY id LIMIT 1')->fetchColumn();$pdo->prepare('INSERT INTO users(name,mobile,email,password_hash,status,is_verified) VALUES("Bonus QR User","9000000099","bonus-qr@example.test",?,"ACTIVE",1)')->execute([password_hash('UserPassword123!',PASSWORD_DEFAULT)]);$user=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO wallets(user_id,balance,bonus_balance,promo_balance,status) VALUES(?,100,0,0,"ACTIVE")')->execute([$user]);
$bonus=wallet_grant_bucket($user,'BONUS','50.00','test-bonus','Signup bonus',$admin,'bonus-integration-key-01',date('Y-m-d H:i:s',time()+3600));assert_ok($bonus['created'],'Bonus grant was not created.');$promo=wallet_grant_bucket($user,'PROMO','15.00','test-promo','QR promo',$admin,'promo-integration-key-01',date('Y-m-d H:i:s',time()+3600));assert_ok($promo['created'],'Promo grant was not created.');$checkout=wallet_checkout($user,'100.00',null,'checkout-integration-key-01');assert_ok($checkout['status']==='SUCCESS'&&$checkout['promo_used']==='15.00'&&$checkout['bonus_used']==='10.00'&&$checkout['real_used']==='75.00','Checkout priority or bonus burn slab failed.');$repeat=wallet_checkout($user,'100.00',null,'checkout-integration-key-01');assert_ok($repeat['created']===false,'Checkout idempotency failed.');
$pdo->prepare("UPDATE wallet_expiry_jobs SET expires_at=DATE_SUB(NOW(),INTERVAL 1 MINUTE) WHERE reference='test-bonus'")->execute([]);$before=(string)$pdo->query("SELECT bonus_balance FROM wallets WHERE user_id={$user}")->fetchColumn();process_wallet_expiries();$after=(string)$pdo->query("SELECT bonus_balance FROM wallets WHERE user_id={$user}")->fetchColumn();assert_ok($before==='40.00'&&$after==='0.00','Bonus expiry reversal failed.');
$pdo->prepare('INSERT INTO hunts(title,slug,start_at,end_at,activation_fee,reward_min,reward_max,status,created_by) VALUES("QR Campaign Hunt","qr-campaign-hunt",DATE_SUB(NOW(),INTERVAL 1 HOUR),DATE_ADD(NOW(),INTERVAL 1 HOUR),0,1,1,"ACTIVE",?)')->execute([$admin]);$hunt=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO hunt_locations(hunt_id,name,latitude,longitude,radius_meters,status) VALUES(?,"QR Spot",12.9716000,77.5946000,100,"ACTIVE")')->execute([$hunt]);$loc=(int)$pdo->lastInsertId();$rawToken=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO hunt_qr_codes(hunt_id,location_id,token_hash,label,status,created_by) VALUES(?,?,?,"Campaign QR","ACTIVE",?)')->execute([$hunt,$loc,hash('sha256',$rawToken),$admin]);$qr=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO qr_campaigns(campaign_code,name,qr_code_id,reward_type,reward_value,ttl_minutes,auto_reversal_enabled,scan_frequency,status,created_by) VALUES("CMP-TEST","Test Campaign",?,"PROMO_CASH",15,30,1,"PER_DEVICE","ACTIVE",?)')->execute([$qr,$admin]);$campaign=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO qr_promo_grants(grant_id,campaign_id,user_id,device_id,amount,status,expires_at) VALUES("PRM-TEST",?,?,"test-device",15,"ACTIVE",DATE_ADD(NOW(),INTERVAL 30 MINUTE))')->execute([$campaign,$user]);assert_ok((int)$pdo->query("SELECT COUNT(*) FROM qr_campaigns WHERE id={$campaign}")->fetchColumn()===1,'QR campaign schema failed.');assert_ok((int)$pdo->query("SELECT COUNT(*) FROM qr_promo_grants WHERE campaign_id={$campaign}")->fetchColumn()===1,'QR promo grant schema failed.');assert_ok((int)$pdo->query("SELECT COUNT(*) FROM wallet_transactions WHERE user_id={$user} AND bucket='PROMO'")->fetchColumn()>=2,'Bucket ledger missing.');echo "Bonus and QR integration assertions passed\n";
