<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli')exit("CLI only\n");
$_SERVER['REQUEST_URI']='/tests/hunt_integration.php';$_SERVER['REMOTE_ADDR']='127.0.0.1';$_SERVER['HTTP_USER_AGENT']='Hunter integration test';
require dirname(__DIR__).'/includes/bootstrap.php';
function check(bool $condition,string $message): void { if(!$condition)throw new RuntimeException($message); }
function rejected(callable $operation,string $message): void { try{$operation();}catch(Throwable){return;}throw new RuntimeException($message); }
$pdo=db();
$role=(int)$pdo->query("SELECT id FROM admin_roles WHERE name='Super Admin'")->fetchColumn();$pdo->prepare('INSERT INTO admins(role_id,name,username,email,password_hash,status) VALUES(?,?,?,?,?,"ACTIVE")')->execute([$role,'Integration Admin','integration-admin','integration-admin@example.test',password_hash('IntegrationPassword123!',PASSWORD_DEFAULT)]);$adminId=(int)$pdo->lastInsertId();
$makeUser=static function(string $name,string $mobile,string $email)use($pdo): int{$pdo->prepare('INSERT INTO users(name,mobile,email,password_hash,status,is_verified) VALUES(?,?,?,?,"ACTIVE",1)')->execute([$name,$mobile,$email,password_hash('UserPassword123!',PASSWORD_DEFAULT)]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO wallets(user_id,balance,status) VALUES(?,0,"ACTIVE")')->execute([$id]);$pdo->prepare('INSERT INTO user_devices(user_id,device_id,status,last_active_at) VALUES(?, ?,"ACTIVE",NOW())')->execute([$id,'device-'.$id]);return $id;};
$userId=$makeUser('Hunt User','9000000001','hunt-user@example.test');$paidUserId=$makeUser('Paid User','9000000002','paid-user@example.test');
$pdo->prepare('INSERT INTO hunts(title,slug,description,rules,start_at,end_at,activation_fee,reward_min,reward_max,status,created_by) VALUES(?,?,"Test","Rules",DATE_SUB(NOW(),INTERVAL 1 DAY),DATE_ADD(NOW(),INTERVAL 2 DAY),100,500,500,"ACTIVE",?)')->execute(['Integration Hunt','integration-hunt',$adminId]);$huntId=(int)$pdo->lastInsertId();
$pdo->prepare('INSERT INTO hunt_locations(hunt_id,name,latitude,longitude,radius_meters,status) VALUES(?,"Test Location",12.9716000,77.5946000,100,"ACTIVE")')->execute([$huntId]);$locationId=(int)$pdo->lastInsertId();$qrToken=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO hunt_qr_codes(hunt_id,location_id,token_hash,label,status,created_by) VALUES(?,?,?,"Test QR","ACTIVE",?)')->execute([$huntId,$locationId,hash('sha256',$qrToken),$adminId]);$qrId=(int)$pdo->lastInsertId();
$secret='ROTATE-1234';$pdo->prepare('INSERT INTO hunt_secret_codes(hunt_id,location_id,code_hash,valid_from,valid_until,status,created_by) VALUES(?,?,?,DATE_SUB(NOW(),INTERVAL 1 HOUR),DATE_ADD(NOW(),INTERVAL 1 HOUR),"ACTIVE",?)')->execute([$huntId,$locationId,password_hash($secret,PASSWORD_DEFAULT),$adminId]);
$pdo->prepare('INSERT INTO hunt_questions(hunt_id,location_id,question_text,question_type,correct_answer_hash,status,created_by) VALUES(?,?,"Capital of Karnataka?","TEXT",?,"ACTIVE",?)')->execute([$huntId,$locationId,answer_hash('Bengaluru'),$adminId]);$questionId=(int)$pdo->lastInsertId();
$activation=activate_hunt_for_user($userId,$huntId,'COUNTER',null,$adminId);check($activation['created']===true,'Counter activation was not created.');
$user=['id'=>$userId,'device_id'=>'device-'.$userId];rejected(fn()=>validate_hunt_scan($user,$qrToken,13.0500,77.7000,10),'Out-of-radius GPS was accepted.');check((int)$pdo->query("SELECT COUNT(*) FROM hunt_scan_attempts WHERE result='REJECTED'")->fetchColumn()>=1,'Rejected scan attempt was not recorded.');
$scan=validate_hunt_scan($user,$qrToken,12.97161,77.59461,10);check($scan['scan_id']>0&&$scan['distance_meters']<100,'Valid QR/GPS scan failed.');rejected(fn()=>validate_hunt_scan($user,$qrToken,12.97161,77.59461,10),'Duplicate QR claim was accepted.');
rejected(fn()=>validate_secret_challenge($user,$scan['scan_id'],'wrong'),'Invalid secret was accepted.');check(validate_secret_challenge($user,$scan['scan_id'],$secret),'Valid secret failed.');rejected(fn()=>validate_question_challenge($user,$scan['scan_id'],$questionId,'Mysuru'),'Wrong answer was accepted.');check(validate_question_challenge($user,$scan['scan_id'],$questionId,' bengaluru '),'Normalized correct answer failed.');
$reward=create_scratch_reward($user,$scan['scan_id']);check($reward['status']==='PENDING'&&$reward['amount']==='500.00','Server reward was not created pending at configured amount.');$rewardDb=$pdo->prepare('SELECT id FROM rewards WHERE reward_id=?');$rewardDb->execute([$reward['reward_id']]);$rewardId=(int)$rewardDb->fetchColumn();decide_reward($rewardId,'APPROVED',null,$adminId);check((string)$pdo->query("SELECT balance FROM wallets WHERE user_id={$userId}")->fetchColumn()==='500.00','Reward approval did not credit wallet exactly once.');rejected(fn()=>decide_reward($rewardId,'APPROVED',null,$adminId),'Duplicate reward approval succeeded.');$credits=$pdo->prepare("SELECT COUNT(*) FROM wallet_transactions WHERE user_id=? AND idempotency_key=?");$credits->execute([$userId,'reward-credit:'.$rewardId]);check((int)$credits->fetchColumn()===1,'Duplicate wallet credit exists.');
$walletId=(int)$pdo->query("SELECT id FROM wallets WHERE user_id={$userId}")->fetchColumn();$withdrawalCode=transaction_code('WDL');$pdo->prepare('INSERT INTO withdrawals(withdrawal_id,user_id,wallet_id,amount,payment_method,payment_account_masked,status) VALUES(?,?,?,150,"UPI","XXXX XXXX 0001","PENDING")')->execute([$withdrawalCode,$userId,$walletId]);$withdrawalId=(int)$pdo->lastInsertId();transition_withdrawal($withdrawalId,'UNDER_REVIEW',null,$adminId);transition_withdrawal($withdrawalId,'APPROVED',null,$adminId);check((string)$pdo->query("SELECT balance FROM wallets WHERE user_id={$userId}")->fetchColumn()==='350.00','Withdrawal approval debit is incorrect.');rejected(fn()=>transition_withdrawal($withdrawalId,'APPROVED',null,$adminId),'Duplicate withdrawal approval succeeded.');
$payment=create_payment_transaction(['id'=>$paidUserId],$huntId,'RAZORPAY','payment-integration-key-0001');$raw=safe_json(['event_id'=>'evt-integration-1','payment_id'=>$payment['payment_id'],'provider_payment_id'=>'provider-pay-1','status'=>'SUCCESS','amount'=>(string)$payment['amount'],'currency'=>'INR']);$signature=hash_hmac('sha256',$raw,(string)$config['razorpay_webhook_secret']);$event=process_payment_webhook('RAZORPAY','evt-integration-1',$payment['payment_id'],'provider-pay-1','SUCCESS',$raw,$signature);check($event['status']==='VERIFIED','Payment webhook was not verified.');$active=$pdo->prepare("SELECT COUNT(*) FROM hunt_user_activations WHERE user_id=? AND hunt_id=? AND activation_type='ONLINE'");$active->execute([$paidUserId,$huntId]);check((int)$active->fetchColumn()===1,'Verified payment did not activate Hunt.');$duplicateEvent=process_payment_webhook('RAZORPAY','evt-integration-1',$payment['payment_id'],'provider-pay-1','SUCCESS',$raw,$signature);check($duplicateEvent['duplicate']===true,'Duplicate payment webhook was not idempotent.');rejected(fn()=>process_payment_webhook('RAZORPAY','evt-bad',$payment['payment_id'],'bad','SUCCESS',$raw,str_repeat('0',64)),'Invalid payment signature was accepted.');
$pdo->prepare('INSERT INTO vendors(vendor_code,name,shop_name,status,created_by) VALUES("VND-TEST","Test Vendor","Test Shop","ACTIVE",?)')->execute([$adminId]);$vendorId=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO vendor_users(vendor_id,name,username,password_hash,status) VALUES(?,"Clerk","clerk-test",?,"ACTIVE")')->execute([$vendorId,password_hash('VendorPassword123!',PASSWORD_DEFAULT)]);$vendorUserId=(int)$pdo->lastInsertId();$vendor=['id'=>$vendorUserId,'vendor_id'=>$vendorId];$pdo->prepare('INSERT INTO gifts(name,total_quantity,status,created_by,valid_from,valid_until) VALUES("Test Gift",2,"ACTIVE",?,DATE_SUB(NOW(),INTERVAL 1 DAY),DATE_ADD(NOW(),INTERVAL 1 DAY))')->execute([$adminId]);$giftId=(int)$pdo->lastInsertId();
$validCode='VALIDCODE123';$pdo->prepare('INSERT INTO reward_codes(code_reference,code_hash,user_id,gift_id,status,expires_at,created_by) VALUES("GFT-VALID",?,?,?,"ACTIVE",DATE_ADD(NOW(),INTERVAL 1 DAY),?)')->execute([hash('sha256',$validCode),$userId,$giftId,$adminId]);$redeemed=redeem_gift_code($vendor,$validCode);check(str_starts_with($redeemed['redemption_id'],'RED-'),'Valid gift code was not redeemed.');rejected(fn()=>redeem_gift_code($vendor,$validCode),'Already-redeemed code succeeded.');$expiredCode='EXPIREDCODE123';$pdo->prepare('INSERT INTO reward_codes(code_reference,code_hash,user_id,gift_id,status,expires_at,created_by) VALUES("GFT-EXPIRED",?,?,?,"ACTIVE",DATE_SUB(NOW(),INTERVAL 1 DAY),?)')->execute([hash('sha256',$expiredCode),$userId,$giftId,$adminId]);rejected(fn()=>redeem_gift_code($vendor,$expiredCode),'Expired code succeeded.');
check((int)$pdo->query('SELECT COUNT(*) FROM gift_redemption_attempts WHERE result="REJECTED"')->fetchColumn()>=2,'Rejected redemption attempts were not logged.');check((int)$pdo->query('SELECT COUNT(*) FROM audit_logs')->fetchColumn()>=7,'Financial/security audit actions are missing.');
echo "Hunt integration assertions passed\n";
