<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/includes/bootstrap.php';
require_permission('qr.generate');

function bulk_csv_rows(string $path): array {
    $fh=fopen($path,'rb'); if(!$fh) throw new RuntimeException('Could not read upload.');
    $headers=fgetcsv($fh); $expected=['spot_name','category_tag','riddle_text','youtube_video_id','correct_answer','reward_type','reward_value','timer_ttl_minutes'];
    $headers=array_map(static fn($v)=>strtolower(trim((string)$v)), $headers?:[]);
    if($headers!==$expected) throw new InvalidArgumentException('CSV headers must exactly match the eight-column specification.');
    $rows=[]; while(($row=fgetcsv($fh))!==false){if(count(array_filter($row,static fn($v)=>trim((string)$v)!==''))===0)continue; if(count($row)!==8)throw new InvalidArgumentException('Every CSV row must contain eight columns.'); $r=array_combine($expected,$row); if(trim((string)$r['spot_name'])==='')throw new InvalidArgumentException('spot_name is required.'); $r['reward_type']=strtoupper(trim((string)$r['reward_type'])); if(!in_array($r['reward_type'],['PROMO_CASH','COUPON_VOUCHER'],true))throw new InvalidArgumentException('reward_type must be PROMO_CASH or COUPON_VOUCHER.'); if(!preg_match('/^\d{1,12}(\.\d{1,2})?$/',trim((string)$r['reward_value'])))throw new InvalidArgumentException('reward_value is invalid.'); $ttl=trim((string)$r['timer_ttl_minutes']); if($ttl!==''&&(!ctype_digit($ttl)||(int)$ttl<1||(int)$ttl>10080))throw new InvalidArgumentException('timer_ttl_minutes must be 1-10080.'); $rows[]=$r; }
    fclose($fh); if(!$rows)throw new InvalidArgumentException('The CSV contains no data rows.'); if(count($rows)>5000)throw new InvalidArgumentException('Maximum 5,000 rows per batch.'); return $rows;
}
function batch_card_svg(string $spot,string $payload): string { $spot=htmlspecialchars($spot,ENT_QUOTES,'UTF-8'); $payload=htmlspecialchars($payload,ENT_QUOTES,'UTF-8'); return '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="720" viewBox="0 0 600 720"><rect width="600" height="720" fill="white"/><rect x="40" y="40" width="520" height="520" fill="none" stroke="black" stroke-width="8"/><path d="M80 80h120v120H80zM400 80h120v120H400zM80 400h120v120H80zM260 260h80v80h-80zM380 260h40v40h-40zM460 340h60v60h-60zM260 420h50v50h-50z" fill="black"/><text x="300" y="610" text-anchor="middle" font-family="Arial" font-size="24">'.$spot.'</text><text x="300" y="650" text-anchor="middle" font-family="Arial" font-size="13">'.substr($payload,0,80).'</text></svg>'; }

if (isset($_GET['download_template'])) {
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="hunter-qr-template.csv"');
    $out=fopen('php://output','w');
    fputcsv($out,['spot_name','category_tag','riddle_text','youtube_video_id','correct_answer','reward_type','reward_value','timer_ttl_minutes']);
    fputcsv($out,['Patna Mall Rack 1','shopping','Find the hidden clue','dQw4w9WgXcQ','Watch','PROMO_CASH','15.00','30']);
    exit;
}

if(($_SERVER['REQUEST_METHOD']??'GET')==='GET' && input('download')){
    require_permission('qr.download'); $id=(int)input('download'); $b=db()->prepare('SELECT * FROM qr_batches WHERE id=?');$b->execute([$id]);$batch=$b->fetch();if(!$batch){http_response_code(404);exit('Batch not found');}
    $items=db()->prepare('SELECT * FROM qr_batch_items WHERE batch_id=? ORDER BY id');$items->execute([$id]);$rows=$items->fetchAll();$tmp=sys_get_temp_dir().'/hunter-batch-'.bin2hex(random_bytes(8));mkdir($tmp,0700,true);$csv=fopen($tmp.'/mapping.csv','wb');fputcsv($csv,['Spot_ID','Spot_Name','Category','Encrypted_URL','Status']);$zip=new ZipArchive();$zip->open($tmp.'/batch.zip',ZipArchive::CREATE);
    foreach($rows as $r){fputcsv($csv,[$r['spot_id'],$r['spot_name'],$r['category_tag'],$r['encrypted_url'],$r['status']]);$zip->addFromString('qr-'.$r['spot_id'].'.svg',batch_card_svg($r['spot_name'],$r['encrypted_url']));}fclose($csv);$zip->addFile($tmp.'/mapping.csv','mapping.csv');$zip->close();audit_log((int)admin()['id'],'QR_BATCH_DOWNLOAD','qr_batches',(string)$id,null,['items'=>count($rows)]);header('Content-Type: application/zip');header('Content-Disposition: attachment; filename="'.preg_replace('/[^A-Za-z0-9_-]/','_', $batch['batch_code']).'.zip"');readfile($tmp.'/batch.zip');exit;
}

if(is_post()){verify_csrf(); try{$pdo=db();$hunt=(int)input('hunt_id');$loc=(int)input('location_id');$check=$pdo->prepare('SELECT h.id,l.id FROM hunts h JOIN hunt_locations l ON l.hunt_id=h.id WHERE h.id=? AND l.id=?');$check->execute([$hunt,$loc]);if(!$check->fetch())throw new InvalidArgumentException('Select a valid Hunt and location.');$mode=strtoupper((string)input('generation_mode'));$rows=$mode==='UPLOAD'?bulk_csv_rows($_FILES['csv']['tmp_name']??''):[];$qty=(int)input('quantity');if($mode==='AUTO_COUNT'){if($qty<1||$qty>5000)throw new InvalidArgumentException('Quantity must be 1-5000.');for($i=1;$i<=$qty;$i++)$rows[]=['spot_name'=>'Spot '.$i,'category_tag'=>trim((string)input('category_tag')),'riddle_text'=>trim((string)input('riddle_text')),'youtube_video_id'=>trim((string)input('youtube_video_id')),'correct_answer'=>'','reward_type'=>strtoupper((string)input('reward_type')),'reward_value'=>trim((string)input('reward_value')),'timer_ttl_minutes'=>trim((string)input('timer_ttl_minutes'))];}
    if(count($rows)>5000)throw new InvalidArgumentException('Maximum 5,000 rows per batch.');$pdo->beginTransaction();$code='BATCH-'.strtoupper(bin2hex(random_bytes(5)));$pdo->prepare('INSERT INTO qr_batches(batch_code,batch_title,category,question_bank_category,generation_mode,quantity,scan_frequency,reward_type,reward_value,hunt_id,location_id,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$code,trim((string)input('batch_title'))?:$code,strtoupper((string)input('category')?:'VIDEO_PAHELI'),trim((string)input('question_bank_category'))?:null,$mode,count($rows),strtoupper((string)input('scan_frequency')?:'PER_DEVICE'),strtoupper((string)($rows[0]['reward_type']??'PROMO_CASH')),(string)($rows[0]['reward_value']??0),$hunt,$loc,admin()['id']]);$batchId=(int)$pdo->lastInsertId();$qr=$pdo->prepare('INSERT INTO hunt_qr_codes(hunt_id,location_id,token_hash,label,status,created_by) VALUES(?,?,?,? ,"ACTIVE",?)');$item=$pdo->prepare('INSERT INTO qr_batch_items(batch_id,spot_id,spot_name,category_tag,riddle_text,youtube_video_id,correct_answer_hash,reward_type,reward_value,timer_ttl_minutes,qr_code_id,encrypted_url) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');foreach($rows as $n=>$r){$token=bin2hex(random_bytes(32));$qr->execute([$hunt,$loc,hash('sha256',$token),$r['spot_name'],admin()['id']]);$qrId=(int)$pdo->lastInsertId();$spotId=$code.'-'.str_pad((string)($n+1),5,'0',STR_PAD_LEFT);$url='app://campaign/riddle?id='.$spotId.'&t='.$token;$ans=trim((string)$r['correct_answer']);$item->execute([$batchId,$spotId,trim((string)$r['spot_name']),trim((string)$r['category_tag']),trim((string)$r['riddle_text']),trim((string)$r['youtube_video_id'])?:null,$ans===''?null:hash('sha256',strtolower($ans)),strtoupper((string)$r['reward_type']),(string)$r['reward_value'],trim((string)$r['timer_ttl_minutes'])?:null,$qrId,$url]);}audit_log((int)admin()['id'],'QR_BATCH_CREATED','qr_batches',(string)$batchId,null,['batch_code'=>$code,'quantity'=>count($rows),'mode'=>$mode]);$pdo->commit();flash('success','Bulk QR batch created. Download the ZIP from the batch list.');}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());}redirect('/admin/qr/bulk.php');}

$hunts=db()->query('SELECT id,title FROM hunts WHERE status IN ("ACTIVE","DRAFT") ORDER BY title')->fetchAll();$batches=db()->query('SELECT b.*,h.title hunt,l.name location,(SELECT COUNT(*) FROM qr_batch_items i WHERE i.batch_id=b.id) item_count,(SELECT COUNT(*) FROM qr_batch_items i WHERE i.batch_id=b.id AND i.status="SCANNED") scanned_count FROM qr_batches b LEFT JOIN hunts h ON h.id=b.hunt_id LEFT JOIN hunt_locations l ON l.id=b.location_id ORDER BY b.id DESC')->fetchAll();$pageTitle='Bulk QR generator';$pageSubtitle='Validated Excel/CSV import and controlled batch downloads';require APP_ROOT.'/includes/header.php';
?>
<section class="panel"><div class="panel-head"><h2>Generate a batch</h2><div class="actions bulk-tools"><a class="btn secondary" href="../hunts/questions_bulk.php">Upload question bank</a><a class="btn secondary" href="../hunts/questions_bulk.php?download_template=1">Download question CSV template</a></div></div><form method="post" enctype="multipart/form-data" class="form-grid"><?=csrf_field()?><div class="field"><label>Batch title</label><input name="batch_title" required maxlength="190"></div><div class="field"><label>Category</label><select name="category"><option>VIDEO_PAHELI</option><option>PRODUCT_SKU</option><option>COUPON_VOUCHER</option><option>BONUS_POINT</option></select></div><div class="field"><label>Hunt</label><select name="hunt_id" required><?php foreach($hunts as $h):?><option value="<?=e($h['id'])?>"><?=e($h['title'])?></option><?php endforeach?></select></div><div class="field"><label>Location ID</label><input type="number" name="location_id" min="1" required></div><div class="field"><label>Question bank category</label><input name="question_bank_category" placeholder="General knowledge / Coaching / Mall Hunt" required></div><div class="field"><label>Generation mode</label><select name="generation_mode"><option>UPLOAD</option><option>AUTO_COUNT</option></select></div><div class="field"><label>Excel/CSV file</label><input type="file" name="csv" accept=".csv,text/csv"></div><div class="field"><label>Auto-count quantity</label><input type="number" name="quantity" min="1" max="5000"></div><div class="field"><label>Question reward type</label><select name="reward_type"><option>PROMO_CASH</option><option>COUPON_VOUCHER</option></select></div><div class="field"><label>Question reward price (₹)</label><input name="reward_value" inputmode="decimal" value="15.00"></div><div class="field"><label>Scan frequency</label><select name="scan_frequency"><option>PER_DEVICE</option><option>SINGLE_USE</option><option>DAILY</option><option>POOL</option></select></div><div class="field full"><p class="help">Upload headers exactly: spot_name, category_tag, riddle_text, youtube_video_id, correct_answer, reward_type, reward_value, timer_ttl_minutes · <a href="?download_template=1">Download sample CSV</a></p><button class="btn">Create batch</button></div></form></section>
<section class="panel"><h2>Batch history</h2><div class="table-wrap"><table><thead><tr><th>Batch</th><th>Category</th><th>Hunt/location</th><th>Generated</th><th>Scanned</th><th>Status</th><th>Download</th></tr></thead><tbody><?php foreach($batches as $b):?><tr><td><?=e($b['batch_code'])?><br><?=e($b['batch_title'])?></td><td><?=e($b['category'])?></td><td><?=e($b['hunt']??'—')?> / <?=e($b['location']??'—')?></td><td><?=e($b['item_count'])?></td><td><?=e($b['scanned_count'])?></td><td><?=e($b['status'])?></td><td><a class="btn small" href="<?=e(app_url('/admin/qr/bulk.php?download='.$b['id']))?>">ZIP + mapping</a></td></tr><?php endforeach?></tbody></table></div></section><?php require APP_ROOT.'/includes/footer.php';
