<?php declare(strict_types=1);
// The complete four-section workflow lives in Master Category Campaigns.
if ($_SERVER['REQUEST_METHOD'] === 'GET') { header('Location: ../campaigns/index.php'); exit; }
require dirname(__DIR__,2).'/includes/bootstrap.php';
require_permission('qr_campaigns.manage');
if(is_post()){
 verify_csrf();
 try{
  $name=trim((string)input('name'));$qr=(int)input('qr_code_id');$reward=trim((string)input('reward_value'));$ttl=trim((string)input('ttl_minutes'));$budget=trim((string)input('budget_limit'));
  if($name===''||!$qr||!preg_match('/^\d{1,16}(\.\d{1,2})?$/',$reward)||decimal_compare($reward,'0.00')<0||($ttl!==''&&((int)$ttl<1||(int)$ttl>10080))||($budget!==''&&(int)$budget<1))throw new InvalidArgumentException('Campaign name, QR, reward, TTL and budget must be valid.');
  $categoryId=(int)input('category_id')?:null;$pdo=db();if($categoryId){$cs=$pdo->prepare('SELECT capacity_limit,status,(SELECT COUNT(*) FROM qr_campaigns WHERE category_id=?) used FROM video_categories WHERE id=?');$cs->execute([$categoryId,$categoryId]);$cat=$cs->fetch();if(!$cat||$cat['status']!=='ACTIVE')throw new InvalidArgumentException('Category bucket is inactive.');if((int)$cat['used']>=(int)$cat['capacity_limit'])throw new InvalidArgumentException('Category QR capacity has been reached.');}$pdo->beginTransaction();$code='CMP-'.strtoupper(bin2hex(random_bytes(5)));$adminId=(int)admin()['id'];
  $sql='INSERT INTO qr_campaigns(campaign_code,name,category_id,qr_code_id,video_id,clue_text,geofence_enabled,reward_type,reward_value,ttl_minutes,auto_reversal_enabled,merchant_id,scan_frequency,budget_limit,opens_at,closes_at,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"ACTIVE",?)';
  $pdo->prepare($sql)->execute([$code,$name,$categoryId,$qr,(int)input('video_id')?:null,trim((string)input('clue_text')),filter_var(input('geofence_enabled'),FILTER_VALIDATE_BOOL)?1:0,strtoupper((string)input('reward_type')),$reward,$ttl===''?null:(int)$ttl,filter_var(input('auto_reversal_enabled'),FILTER_VALIDATE_BOOL)?1:0,(int)input('merchant_id')?:null,strtoupper((string)input('scan_frequency')),$budget===''?null:(int)$budget,trim((string)input('opens_at'))?:null,trim((string)input('closes_at'))?:null,$adminId]);
  $id=(int)$pdo->lastInsertId();audit_log($adminId,'QR_CAMPAIGN_CREATED','qr_campaigns',(string)$id,null,['campaign_code'=>$code,'reward_type'=>input('reward_type')]);$pdo->commit();flash('success','QR campaign created.');
 }catch(Throwable $e){if(db()->inTransaction())db()->rollBack();flash('error',$e->getMessage());}redirect('/admin/qr/index.php');
}
$categories=db()->query('SELECT id,name FROM video_categories WHERE status="ACTIVE" ORDER BY name')->fetchAll();$qrs=db()->query('SELECT q.id,q.label,h.title hunt,l.name location FROM hunt_qr_codes q JOIN hunts h ON h.id=q.hunt_id JOIN hunt_locations l ON l.id=q.location_id WHERE q.status="ACTIVE" ORDER BY q.id DESC')->fetchAll();$videos=db()->query('SELECT id,title FROM hunt_videos WHERE status="ACTIVE" ORDER BY title')->fetchAll();$vendors=db()->query('SELECT id,shop_name FROM vendors WHERE status="ACTIVE" ORDER BY shop_name')->fetchAll();$items=db()->query('SELECT c.*,q.label,h.title hunt,l.name location,vc.name category,v.shop_name vendor FROM qr_campaigns c JOIN hunt_qr_codes q ON q.id=c.qr_code_id JOIN hunts h ON h.id=q.hunt_id JOIN hunt_locations l ON l.id=q.location_id LEFT JOIN video_categories vc ON vc.id=c.category_id LEFT JOIN vendors v ON v.id=c.merchant_id ORDER BY c.id DESC')->fetchAll();$pageTitle='QR campaigns';$pageSubtitle='Programmable physical QR spots with reward, TTL, vendor, budget and schedule controls';require APP_ROOT.'/includes/header.php';
?>
<section class="panel"><form method="post" class="form-grid"><?=csrf_field()?><div class="field"><label>Campaign / spot name</label><input name="name" placeholder="Patna Central Mall - Parle-G Rack" required></div><div class="field"><label>Master QR</label><select name="qr_code_id" required><?php foreach($qrs as $q):?><option value="<?=e($q['id'])?>"><?=e(($q['label']?:'#'.$q['id']).' · '.$q['hunt'].' · '.$q['location'])?></option><?php endforeach?></select></div><div class="field"><label>Category</label><select name="category_id"><option value="">Any</option><?php foreach($categories as $c):?><option value="<?=e($c['id'])?>"><?=e($c['name'])?></option><?php endforeach?></select></div><div class="field"><label>Video</label><select name="video_id"><option value="">None</option><?php foreach($videos as $v):?><option value="<?=e($v['id'])?>"><?=e($v['title'])?></option><?php endforeach?></select></div><div class="field full"><label>Clue / instructions</label><textarea name="clue_text" placeholder="Hindi / English instructions"></textarea></div><div class="field"><label>Geofence</label><select name="geofence_enabled"><option value="1">YES</option><option value="0">NO</option></select></div><div class="field"><label>Reward type</label><select name="reward_type"><option>PROMO_CASH</option><option>REWARD_COINS</option><option>VENDOR_VOUCHER</option></select></div><div class="field"><label>Reward value</label><input name="reward_value" inputmode="decimal" value="15.00" required></div><div class="field"><label>Time lock TTL (minutes)</label><input type="number" name="ttl_minutes" min="1" max="10080" value="30"></div><div class="field"><label>Auto reversal</label><select name="auto_reversal_enabled"><option value="1">ON</option><option value="0">OFF</option></select></div><div class="field"><label>Merchant / cashier</label><select name="merchant_id"><option value="">Any</option><?php foreach($vendors as $v):?><option value="<?=e($v['id'])?>"><?=e($v['shop_name'])?></option><?php endforeach?></select></div><div class="field"><label>Scan frequency</label><select name="scan_frequency"><option>PER_DEVICE</option><option>DAILY</option><option>UNLIMITED</option></select></div><div class="field"><label>Budget pool scans</label><input type="number" name="budget_limit" min="1" placeholder="First 500 users"></div><div class="field"><label>Opens at</label><input type="time" name="opens_at"></div><div class="field"><label>Closes at</label><input type="time" name="closes_at"></div><div class="field full"><button class="btn">Create campaign</button></div></form></section>
<section class="panel"><h2>Campaigns</h2><div class="table-wrap"><table><thead><tr><th>Code</th><th>Spot</th><th>Category/video</th><th>Reward</th><th>TTL</th><th>Frequency</th><th>Budget</th><th>Merchant</th><th>Status</th></tr></thead><tbody><?php foreach($items as $c):?><tr><td><?=e($c['campaign_code'])?></td><td><?=e($c['name'])?><br><small><?=e($c['location'])?></small></td><td><?=e($c['category']??'—')?><br><?=e($c['video']??'—')?></td><td><?=e($c['reward_type'])?><br><?=money($c['reward_value'])?></td><td><?=e($c['ttl_minutes']??'—')?> min<br><?=e($c['auto_reversal_enabled']?'Auto reverse':'Keep')?></td><td><?=e($c['scan_frequency'])?></td><td><?=e($c['claimed_count'])?> / <?=e($c['budget_limit']??'∞')?></td><td><?=e($c['vendor']??'Any')?></td><td><span class="badge <?=strtolower(e($c['status']))?>"><?=e($c['status'])?></span></td></tr><?php endforeach?></tbody></table><?php if(!$items):?><div class="empty">No QR campaigns configured.</div><?php endif?></div></section><?php require APP_ROOT.'/includes/footer.php';
