<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/includes/bootstrap.php';
require_permission('wallet.view');
$id=filter_var(input('id'),FILTER_VALIDATE_INT); if(!$id){http_response_code(404);exit('Not found');}
$pdo=db(); $s=$pdo->prepare('SELECT * FROM users WHERE id=?'); $s->execute([$id]); $user=$s->fetch(); if(!$user){http_response_code(404);exit('Customer not found');}
$s=$pdo->prepare('SELECT * FROM wallets WHERE user_id=?');$s->execute([$id]);$wallet=$s->fetch()?:['balance'=>0,'bonus_balance'=>0,'promo_balance'=>0];
$s=$pdo->prepare('SELECT COUNT(*) count,COALESCE(SUM(discount_amount),0) value FROM coupons WHERE user_id=? AND status="ACTIVE" AND (expires_at IS NULL OR expires_at>NOW())');$s->execute([$id]);$coupons=$s->fetch()?:['count'=>0,'value'=>0];
$s=$pdo->prepare('SELECT COUNT(*) FROM user_devices WHERE user_id=? AND status="ACTIVE"');$s->execute([$id]);$devices=(int)$s->fetchColumn();
$q=trim((string)input('q'));$from=trim((string)input('from'));$to=trim((string)input('to'));$pocket=strtoupper(trim((string)input('pocket')));$where=['t.user_id=?'];$params=[$id];
if($q!==''){$where[]='(t.transaction_id LIKE ? OR t.description LIKE ? OR t.reference LIKE ?)';$params=array_merge($params,array_fill(0,3,'%'.$q.'%'));}if(in_array($pocket,['REAL','BONUS','PROMO'],true)){$where[]='t.bucket=?';$params[]=$pocket;}if($from!==''&&valid_date($from)){$where[]='t.created_at>=?';$params[]=$from;}if($to!==''&&valid_date($to)){$where[]='t.created_at<DATE_ADD(?,INTERVAL 1 DAY)';$params[]=$to;}
$s=$pdo->prepare('SELECT * FROM wallet_transactions t WHERE '.implode(' AND ',$where).' ORDER BY t.id DESC LIMIT 200');$s->execute($params);$rows=$s->fetchAll();$pageTitle='Customer financial dashboard';$pageSubtitle='Lifetime balances, security status and passbook';require APP_ROOT.'/includes/header.php';
?>
<section class="customer-dashboard"><div class="customer-section-heading"><h2>2. CUSTOMER PROFILE DETAILS &amp; LIFETIME BALANCES SUMMARY</h2><strong>LIVE FINANCIAL DASHBOARD</strong></div>
<div class="customer-profile-grid"><article class="customer-profile-box profile-box"><h3><?=e($user['name'])?> (USR_<?=e((string)$user['id'])?>)</h3><p><b>Email:</b> <?=e($user['email']?:'Not provided')?> <span>|</span> <b>Phone:</b> <?=e($user['mobile']?:'Not provided')?></p><p><b>Address:</b> Not provided</p><p><b>Joined Date &amp; Time:</b> <?=e(date('d-M-Y, h:i A',strtotime((string)$user['created_at'])))?></p></article><article class="customer-profile-box security-box"><h3>Security &amp; Device Status</h3><p><b>KYC / UPI Status:</b> <span class="status-dot"></span><?=($user['is_verified']?'Verified account':'Pending verification')?></p><p><b>Device Lock:</b> SHA-256 (<?=e((string)$devices)?> active device<?= $devices===1?'':'s' ?>)</p><p><b>Bonus Usage Rule:</b> Managed by wallet policy</p></article></div>
<div class="summary-grid"><article class="stat-card real-card"><span>TOTAL REAL BALANCE</span><strong><?=money($wallet['balance'])?></strong></article><article class="stat-card bonus-card"><span>TOTAL BONUS BALANCE</span><strong><?=money((float)$wallet['bonus_balance']+(float)$wallet['promo_balance'])?></strong></article><article class="stat-card coupon-card"><span>TOTAL ACTIVE COUPONS</span><strong><?=e((string)$coupons['count'])?> Active (<?=money($coupons['value'])?>)</strong></article><article class="stat-card coin-card"><span>TOTAL Q-COINS TRACKER</span><strong>Not configured</strong></article></div>
<section class="panel customer-passbook"><div class="panel-head"><h2>🔍 FILTER PASSBOOK</h2><a class="btn" href="index.php">Back to wallet ledger</a></div><form class="filters customer-filter"><input name="q" value="<?=e($q)?>" placeholder="Search by Txn ID, event or date..."><select name="pocket"><option value="">All pockets</option><?php foreach(['REAL'=>'Real cash','BONUS'=>'Bonus','PROMO'=>'Promo'] as $key=>$label):?><option value="<?=$key?>" <?=$pocket===$key?'selected':''?>><?=$label?></option><?php endforeach?></select><input type="date" name="from" value="<?=e($from)?>"><input type="date" name="to" value="<?=e($to)?>"><input type="hidden" name="id" value="<?=e((string)$id)?>"><button class="btn">Filter</button></form><div class="table-wrap"><table class="customer-ledger"><thead><tr><th>TXN ID</th><th>DATE &amp; TIME</th><th>EVENT / CATEGORY DESCRIPTION</th><th>REAL CASH (₹)</th><th>BONUS AMOUNT (₹)</th><th>TYPE</th><th>APPLIED FORMULA / SPLIT RULE</th><th>STATUS</th></tr></thead><tbody><?php foreach($rows as $row):$debit=in_array($row['type'],['DEBIT','WITHDRAWAL','BONUS_DEBIT','PROMO_DEBIT'],true);$bonus=in_array($row['bucket'],['BONUS','PROMO'],true);$sign=$debit?'-':'+';$event=trim((string)($row['description']?:$row['reference']?:'Ledger adjustment'));$ts=strtotime((string)$row['created_at']);?><tr><td><?=e($row['transaction_id'])?></td><td><?=e($ts?date('d-M-Y, h:i A',$ts):(string)$row['created_at'])?></td><td><?=e($event)?></td><td class="<?=$bonus?'':($debit?'ledger-negative':'ledger-positive')?>"><?=$bonus?'₹0.00':$sign.money($row['amount'])?></td><td class="<?=$bonus?($debit?'ledger-negative':'ledger-positive'):''?>"><?=$bonus?$sign.money($row['amount']):'₹0.00'?></td><td><span class="type-pill <?=$debit?'debit':'credit'?>"><?=$debit?'- DEBIT':'+ CREDIT'?></span></td><td><?=e($event)?></td><td><span class="badge <?=strtolower(e((string)$row['status']))?>"><?=e($row['status'])?></span></td></tr><?php endforeach?></tbody></table><?php if(!$rows):?><div class="empty">No transactions found.</div><?php endif?></div></section></section><?php require APP_ROOT.'/includes/footer.php';
