<?php
declare(strict_types=1);
require dirname(__DIR__).'/_bootstrap.php';
require_post();
$user=api_user();api_rate_limit($user,'qr.campaign.scan',10,60);$d=json_input();$token=trim((string)($d['qr_token']??''));
if(!preg_match('/^[a-f0-9]{64}$/i',$token))json_response(false,'A valid QR token is required',null,422);
$pdo=db();$pdo->beginTransaction();
try{$s=$pdo->prepare('SELECT c.*,q.hunt_id,q.location_id,l.latitude,l.longitude,l.radius_meters,l.status location_status,h.status hunt_status,vc.status category_status FROM qr_campaigns c JOIN hunt_qr_codes q ON q.id=c.qr_code_id JOIN hunt_locations l ON l.id=q.location_id JOIN hunts h ON h.id=q.hunt_id LEFT JOIN video_categories vc ON vc.id=c.category_id WHERE q.token_hash=? FOR UPDATE');$s->execute([hash('sha256',$token)]);$c=$s->fetch();
if(!$c||$c['status']!=='ACTIVE'||$c['hunt_status']!=='ACTIVE'||$c['location_status']!=='ACTIVE'||($c['category_id']!==null&&$c['category_status']!=='ACTIVE'))throw new RuntimeException('CAMPAIGN_PAUSED: This category or campaign is inactive.');$now=date('H:i:s');if(($c['opens_at']&&$now<$c['opens_at'])||($c['closes_at']&&$now>$c['closes_at']))throw new RuntimeException('Campaign is currently closed.');if($c['budget_limit']!==null&&(int)$c['claimed_count']>=(int)$c['budget_limit'])throw new RuntimeException('Campaign budget has been exhausted.');
$distance=haversine_distance((float)($d['latitude']??0),(float)($d['longitude']??0),(float)$c['latitude'],(float)$c['longitude']);if((int)$c['geofence_enabled']===1&&$distance>(float)$c['radius_meters'])throw new RuntimeException('You are outside the campaign geofence.');$where='campaign_id=? AND user_id=?';$params=[(int)$c['id'],$user['id']];if($c['scan_frequency']==='PER_DEVICE'){$where.=' AND device_id=?';$params[]=$user['device_id'];}elseif($c['scan_frequency']==='DAILY')$where.=' AND created_at>=CURDATE()';$old=$pdo->prepare("SELECT id FROM qr_promo_grants WHERE {$where} LIMIT 1");$old->execute($params);if($old->fetch())throw new RuntimeException('This campaign has already been claimed for the current rule.');
$grant=transaction_code('PRM');$expires=$c['ttl_minutes']?date('Y-m-d H:i:s',time()+((int)$c['ttl_minutes']*60)):null;$pdo->prepare('INSERT INTO qr_promo_grants(grant_id,campaign_id,user_id,device_id,amount,status,expires_at) VALUES(?,?,?,?,?,"ACTIVE",?)')->execute([$grant,$c['id'],$user['id'],$user['device_id'],$c['reward_value'],$expires]);$pdo->prepare('UPDATE qr_campaigns SET claimed_count=claimed_count+1 WHERE id=?')->execute([$c['id']]);if($c['reward_type']==='PROMO_CASH')wallet_bucket_apply_in_transaction($pdo,(int)$user['id'],'PROMO',(string)$c['reward_value'],$grant,'QR promo grant',null,'qr-promo:'.$grant,'CREDIT');if($expires&&$c['auto_reversal_enabled']){$w=$pdo->prepare('SELECT id FROM wallets WHERE user_id=?');$w->execute([$user['id']]);$pdo->prepare('INSERT INTO wallet_expiry_jobs(bucket,wallet_id,amount,reference,expires_at) VALUES("PROMO",?,?,?,?)')->execute([$w->fetchColumn(),$c['reward_value'],$grant,$expires]);}$pdo->commit();log_security((int)$user['id'],'QR_PROMO_GRANTED','LOW','QR campaign promo granted',['campaign_id'=>$c['id'],'grant_id'=>$grant,'device_id'=>$user['device_id']]);json_response(true,'Promo reward unlocked; complete the merchant purchase before the timer expires',['grant_id'=>$grant,'campaign_code'=>$c['campaign_code'],'amount'=>$c['reward_value'],'expires_at'=>$expires,'video_id'=>$c['video_id'],'clue_text'=>$c['clue_text'],'distance_meters'=>round($distance,2)],201);
}catch(InvalidArgumentException $e){if($pdo->inTransaction())$pdo->rollBack();json_response(false,$e->getMessage(),null,422);}catch(RuntimeException $e){if($pdo->inTransaction())$pdo->rollBack();log_security((int)$user['id'],'QR_CAMPAIGN_REJECTED','MEDIUM',$e->getMessage(),['device_id'=>$user['device_id']]);json_response(false,$e->getMessage(),null,409);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
