-- Hunter Wallet production-safe incremental update
-- Select the target database in phpMyAdmin before importing this file.
-- This file does not create/drop a database and does not insert demo data.
SET @db := DATABASE();
CREATE TABLE IF NOT EXISTS hunt_user_activations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, hunt_id BIGINT UNSIGNED NOT NULL, status ENUM('ACTIVE','REVOKED','COMPLETED') NOT NULL DEFAULT 'ACTIVE', activated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NULL, INDEX idx_activation_status(status));
CREATE TABLE IF NOT EXISTS qr_promo_grants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, grant_id VARCHAR(50) NOT NULL UNIQUE, campaign_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, device_id VARCHAR(190) NOT NULL, amount DECIMAL(18,2) NOT NULL, status ENUM('ACTIVE','SPENT','EXPIRED','REVERSED') NOT NULL DEFAULT 'ACTIVE', expires_at DATETIME NULL, spent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_campaign_user_device(campaign_id,user_id,device_id));
CREATE TABLE IF NOT EXISTS merchant_settlements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, settlement_id VARCHAR(60) NOT NULL UNIQUE, checkout_id VARCHAR(50) NOT NULL UNIQUE, merchant_id BIGINT UNSIGNED NOT NULL, bill_amount DECIMAL(18,2) NOT NULL, promo_amount DECIMAL(18,2) NOT NULL DEFAULT 0, customer_paid DECIMAL(18,2) NOT NULL DEFAULT 0, platform_fee DECIMAL(18,2) NOT NULL DEFAULT 0, merchant_amount DECIMAL(18,2) NOT NULL DEFAULT 0, status ENUM('PENDING','SETTLED','REVERSED') NOT NULL DEFAULT 'PENDING', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, settled_at DATETIME NULL, INDEX idx_settlement_status(status,created_at));
CREATE TABLE IF NOT EXISTS qr_campaigns (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, campaign_code VARCHAR(50) NOT NULL UNIQUE, name VARCHAR(190) NOT NULL, category_id BIGINT UNSIGNED NULL, qr_code_id BIGINT UNSIGNED NOT NULL UNIQUE, video_id BIGINT UNSIGNED NULL, clue_text TEXT NULL, geofence_enabled TINYINT(1) NOT NULL DEFAULT 0, reward_type ENUM('PROMO_CASH','REWARD_COINS','VENDOR_VOUCHER') NOT NULL DEFAULT 'PROMO_CASH', reward_value DECIMAL(18,2) NOT NULL DEFAULT 0, ttl_minutes INT UNSIGNED NULL, auto_reversal_enabled TINYINT(1) NOT NULL DEFAULT 0, merchant_id BIGINT UNSIGNED NULL, scan_frequency ENUM('PER_DEVICE','DAILY','UNLIMITED') NOT NULL DEFAULT 'PER_DEVICE', budget_limit INT UNSIGNED NULL, claimed_count INT UNSIGNED NOT NULL DEFAULT 0, opens_at TIME NULL, closes_at TIME NULL, status ENUM('ACTIVE','INACTIVE','EXPIRED') NOT NULL DEFAULT 'ACTIVE', created_by INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_qr_campaign_status(status));
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='video_categories') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='video_categories' AND column_name='character_name'),'ALTER TABLE video_categories ADD COLUMN character_name VARCHAR(190) NULL AFTER slug','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS spot_campaigns (spot_id VARCHAR(64) PRIMARY KEY, master_token_hash CHAR(64) NOT NULL UNIQUE, spot_name VARCHAR(255) NOT NULL, category_id BIGINT UNSIGNED NULL, question_mode ENUM('SINGLE','COLLECTION') NOT NULL DEFAULT 'SINGLE', question_id BIGINT UNSIGNED NULL, collection_id BIGINT UNSIGNED NULL, target_scope ENUM('ALL_PUBLIC','WHITELIST','NEW_USER') NOT NULL DEFAULT 'ALL_PUBLIC', whitelisted_users JSON NULL, city_zone VARCHAR(128) NULL, venue_name VARCHAR(255) NULL, gps_mode ENUM('GPS_REQUIRED','DESK_STUDY') NOT NULL DEFAULT 'GPS_REQUIRED', latitude DECIMAL(10,7) NOT NULL DEFAULT 0, longitude DECIMAL(10,7) NOT NULL DEFAULT 0, proximity_alert_radius INT UNSIGNED NOT NULL DEFAULT 30, scanner_unlock_radius INT UNSIGNED NOT NULL DEFAULT 20, indoor_micro_clue TEXT NULL, reward_type ENUM('PROMO_CASH','COUPON_VOUCHER','DIRECT_CASH','MILESTONE') NOT NULL DEFAULT 'PROMO_CASH', reward_amount DECIMAL(18,2) NOT NULL DEFAULT 15, min_cart_value DECIMAL(18,2) NOT NULL DEFAULT 300, ttl_minutes INT UNSIGNED NOT NULL DEFAULT 30, auto_reversal TINYINT(1) NOT NULL DEFAULT 1, max_budget_scans INT UNSIGNED NOT NULL DEFAULT 500, scan_frequency_policy ENUM('PER_DEVICE','SINGLE_USE','DAILY','POOL') NOT NULL DEFAULT 'PER_DEVICE', is_active TINYINT(1) NOT NULL DEFAULT 1, created_by INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_spot_active(is_active,category_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS riddle_pool (riddle_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, spot_id VARCHAR(64) NOT NULL, riddle_text TEXT NOT NULL, primary_answer VARCHAR(128) NOT NULL, synonyms JSON NOT NULL, yt_video_id VARCHAR(32) NULL, weight_percentage INT UNSIGNED NOT NULL DEFAULT 100, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_riddle_spot(spot_id,weight_percentage), FOREIGN KEY(spot_id) REFERENCES spot_campaigns(spot_id) ON DELETE CASCADE) ENGINE=InnoDB;
-- Add columns to installations running MySQL versions without ADD COLUMN IF NOT EXISTS.
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='question_mode'), 'ALTER TABLE riddle_pool ADD COLUMN question_mode ENUM(''SINGLE'',''MULTIPLE'') NOT NULL DEFAULT ''SINGLE'' AFTER spot_id', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='instruction_text'), 'ALTER TABLE riddle_pool ADD COLUMN instruction_text TEXT NULL AFTER riddle_text', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='channel_url'), 'ALTER TABLE riddle_pool ADD COLUMN channel_url VARCHAR(500) NULL AFTER yt_video_id', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='answer_time_seconds'), 'ALTER TABLE riddle_pool ADD COLUMN answer_time_seconds INT UNSIGNED NOT NULL DEFAULT 60 AFTER channel_url', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS scan_audit_ledger (audit_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, device_hash VARCHAR(128) NOT NULL, user_id BIGINT UNSIGNED NOT NULL, spot_id VARCHAR(64) NOT NULL, riddle_id BIGINT UNSIGNED NULL, user_input_answer TEXT NULL, is_correct TINYINT(1) NOT NULL DEFAULT 0, attempt_count INT UNSIGNED NOT NULL DEFAULT 1, gps_lat_submitted DECIMAL(10,7) NULL, gps_lng_submitted DECIMAL(10,7) NULL, distance_calculated_m DECIMAL(12,2) NULL, status ENUM('PASS','WRONG_ATTEMPT','BLOCKED_DEVICE','EXHAUSTED','EXPIRED','SETTLED') NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_scan_audit_spot(spot_id,created_at), INDEX idx_scan_device(device_hash,spot_id)) ENGINE=InnoDB;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='logo_path'),'ALTER TABLE vendors ADD COLUMN logo_path VARCHAR(255) NULL AFTER address','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='cover_image_path'),'ALTER TABLE vendors ADD COLUMN cover_image_path VARCHAR(255) NULL AFTER logo_path','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='spot_campaigns') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='spot_campaigns' AND column_name='gps_mode'),'ALTER TABLE spot_campaigns ADD COLUMN gps_mode ENUM(''GPS_REQUIRED'',''DESK_STUDY'') NOT NULL DEFAULT ''GPS_REQUIRED'' AFTER venue_name','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
INSERT IGNORE INTO system_settings(`key`,`value`,is_secret) VALUES ('brand_name','Hunter Wallet',0),('brand_tagline','Secure administration portal',0),('theme_mode','light',0),('primary_color','#12304a',0),('accent_color','#24c79a',0),('default_currency','INR',0),('smtp_port','587',0),('session_timeout','1800',0);
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='qr_batches') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='qr_batches' AND column_name='question_bank_category'), 'ALTER TABLE qr_batches ADD COLUMN question_bank_category VARCHAR(190) NULL AFTER category', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='status'), 'ALTER TABLE riddle_pool ADD COLUMN status ENUM(''ACTIVE'',''INACTIVE'') NOT NULL DEFAULT ''ACTIVE'' AFTER weight_percentage', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='riddle_pool') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='riddle_pool' AND column_name='updated_at'), 'ALTER TABLE riddle_pool ADD COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS question_collections (collection_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, collection_name VARCHAR(190) NOT NULL, spot_id VARCHAR(64) NOT NULL, description TEXT NULL, rotation_method ENUM('SEQUENTIAL','RANDOM','RANDOM_NO_REPEAT','ROUND_ROBIN','WEIGHTED') NOT NULL DEFAULT 'SEQUENTIAL', questions_per_session INT UNSIGNED NOT NULL DEFAULT 1, status ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE', created_by INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(spot_id) REFERENCES spot_campaigns(spot_id) ON DELETE CASCADE, FOREIGN KEY(created_by) REFERENCES admins(id), INDEX idx_collection_status(status,spot_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS question_collection_items (collection_id BIGINT UNSIGNED NOT NULL, riddle_id BIGINT UNSIGNED NOT NULL, question_order INT UNSIGNED NOT NULL DEFAULT 1, PRIMARY KEY(collection_id,riddle_id), UNIQUE KEY uq_collection_order(collection_id,question_order), FOREIGN KEY(collection_id) REFERENCES question_collections(collection_id) ON DELETE CASCADE, FOREIGN KEY(riddle_id) REFERENCES riddle_pool(riddle_id) ON DELETE CASCADE) ENGINE=InnoDB;
INSERT INTO riddle_pool(spot_id,question_mode,riddle_text,instruction_text,primary_answer,synonyms,yt_video_id,channel_url,answer_time_seconds,status)
SELECT s.spot_id,'SINGLE','Mujhe pehno toh waqt rukta nahi, batao main kaun?','Submit one answer within the time limit.','Watch','["ghadi","clock","samay"]','dQw4w9WgXcQ','https://youtube.com/@example',60,'ACTIVE'
FROM spot_campaigns s WHERE NOT EXISTS (SELECT 1 FROM riddle_pool r WHERE r.spot_id=s.spot_id);
INSERT INTO question_collections(collection_name,spot_id,description,rotation_method,questions_per_session,status,created_by)
SELECT CONCAT('Sample collection - ',s.spot_name),s.spot_id,'Sample collection for testing the rotation engine','SEQUENTIAL',1,'ACTIVE',a.id
FROM spot_campaigns s JOIN admins a ON 1=1
WHERE NOT EXISTS (SELECT 1 FROM question_collections c WHERE c.spot_id=s.spot_id) ORDER BY a.id LIMIT 1;
INSERT IGNORE INTO question_collection_items(collection_id,riddle_id,question_order)
SELECT c.collection_id,r.riddle_id,1 FROM question_collections c JOIN riddle_pool r ON r.spot_id=c.spot_id
WHERE c.collection_name LIKE 'Sample collection - %' ORDER BY r.riddle_id LIMIT 1;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='spot_campaigns') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='spot_campaigns' AND column_name='question_mode'), 'ALTER TABLE spot_campaigns ADD COLUMN question_mode ENUM(''SINGLE'',''COLLECTION'') NOT NULL DEFAULT ''SINGLE'' AFTER category_id', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='spot_campaigns') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='spot_campaigns' AND column_name='question_id'), 'ALTER TABLE spot_campaigns ADD COLUMN question_id BIGINT UNSIGNED NULL AFTER question_mode', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='spot_campaigns') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='spot_campaigns' AND column_name='collection_id'), 'ALTER TABLE spot_campaigns ADD COLUMN collection_id BIGINT UNSIGNED NULL AFTER question_id', 'SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
INSERT IGNORE INTO admin_permissions(code,description) VALUES ('security.governance','View Security & Governance dashboard and staff controls');
INSERT IGNORE INTO admin_role_permissions(role_id,permission_id) SELECT r.id,p.id FROM admin_roles r JOIN admin_permissions p ON p.code='security.governance' WHERE r.name='Super Admin';
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='latitude'),'ALTER TABLE vendors ADD COLUMN latitude DECIMAL(10,7) NULL AFTER address','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='longitude'),'ALTER TABLE vendors ADD COLUMN longitude DECIMAL(10,7) NULL AFTER latitude','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='owner_name'),'ALTER TABLE vendors ADD COLUMN owner_name VARCHAR(190) NULL AFTER shop_name','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='owner_address'),'ALTER TABLE vendors ADD COLUMN owner_address VARCHAR(500) NULL AFTER owner_name','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='gstin'),'ALTER TABLE vendors ADD COLUMN gstin VARCHAR(30) NULL AFTER owner_address','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='identity_proof_path'),'ALTER TABLE vendors ADD COLUMN identity_proof_path VARCHAR(255) NULL AFTER gstin','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='address_proof_path'),'ALTER TABLE vendors ADD COLUMN address_proof_path VARCHAR(255) NULL AFTER identity_proof_path','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='bank_account_holder'),'ALTER TABLE vendors ADD COLUMN bank_account_holder VARCHAR(190) NULL AFTER address_proof_path','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='bank_account_number'),'ALTER TABLE vendors ADD COLUMN bank_account_number VARCHAR(80) NULL AFTER bank_account_holder','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='bank_ifsc'),'ALTER TABLE vendors ADD COLUMN bank_ifsc VARCHAR(20) NULL AFTER bank_account_number','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='bank_branch'),'ALTER TABLE vendors ADD COLUMN bank_branch VARCHAR(120) NULL AFTER bank_ifsc','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='settlement_upi'),'ALTER TABLE vendors ADD COLUMN settlement_upi VARCHAR(190) NULL AFTER bank_branch','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='commission_rate'),'ALTER TABLE vendors ADD COLUMN commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0 AFTER settlement_upi','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='escrow_balance'),'ALTER TABLE vendors ADD COLUMN escrow_balance DECIMAL(18,2) NOT NULL DEFAULT 0 AFTER commission_rate','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='settlement_cycle'),'ALTER TABLE vendors ADD COLUMN settlement_cycle ENUM(''DAILY'',''WEEKLY'',''MONTHLY'') NOT NULL DEFAULT ''DAILY'' AFTER escrow_balance','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='proximity_radius_m'),'ALTER TABLE vendors ADD COLUMN proximity_radius_m INT UNSIGNED NOT NULL DEFAULT 300 AFTER longitude','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='business_category'),'ALTER TABLE vendors ADD COLUMN business_category VARCHAR(120) NULL AFTER shop_name','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='video_categories') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='video_categories' AND column_name='commission_type'),'ALTER TABLE video_categories ADD COLUMN commission_type ENUM(''PERCENTAGE'',''FIXED'') NOT NULL DEFAULT ''PERCENTAGE'' AFTER slug','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='video_categories') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='video_categories' AND column_name='platform_commission_rate'),'ALTER TABLE video_categories ADD COLUMN platform_commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0 AFTER commission_type','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='video_categories') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='video_categories' AND column_name='customer_reward_rate'),'ALTER TABLE video_categories ADD COLUMN customer_reward_rate DECIMAL(5,2) NOT NULL DEFAULT 0 AFTER platform_commission_rate','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
