-- Hunter Wallet production-safe incremental update
-- Select the target database in phpMyAdmin before importing this file.
-- This file does not create/drop a database and does not insert demo data.
SET @db := DATABASE();
CREATE TABLE IF NOT EXISTS hunt_user_activations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, hunt_id BIGINT UNSIGNED NOT NULL, status ENUM('ACTIVE','REVOKED','COMPLETED') NOT NULL DEFAULT 'ACTIVE', activated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NULL, INDEX idx_activation_status(status));
CREATE TABLE IF NOT EXISTS qr_promo_grants (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, grant_id VARCHAR(50) NOT NULL UNIQUE, campaign_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, device_id VARCHAR(190) NOT NULL, amount DECIMAL(18,2) NOT NULL, status ENUM('ACTIVE','SPENT','EXPIRED','REVERSED') NOT NULL DEFAULT 'ACTIVE', expires_at DATETIME NULL, spent_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_campaign_user_device(campaign_id,user_id,device_id));
CREATE TABLE IF NOT EXISTS merchant_settlements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, settlement_id VARCHAR(60) NOT NULL UNIQUE, checkout_id VARCHAR(50) NOT NULL UNIQUE, merchant_id BIGINT UNSIGNED NOT NULL, bill_amount DECIMAL(18,2) NOT NULL, promo_amount DECIMAL(18,2) NOT NULL DEFAULT 0, customer_paid DECIMAL(18,2) NOT NULL DEFAULT 0, platform_fee DECIMAL(18,2) NOT NULL DEFAULT 0, merchant_amount DECIMAL(18,2) NOT NULL DEFAULT 0, status ENUM('PENDING','SETTLED','REVERSED') NOT NULL DEFAULT 'PENDING', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, settled_at DATETIME NULL, INDEX idx_settlement_status(status,created_at));
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='video_categories') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='video_categories' AND column_name='character_name'),'ALTER TABLE video_categories ADD COLUMN character_name VARCHAR(190) NULL AFTER slug','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
CREATE TABLE IF NOT EXISTS spot_campaigns (spot_id VARCHAR(64) PRIMARY KEY, master_token_hash CHAR(64) NOT NULL UNIQUE, spot_name VARCHAR(255) NOT NULL, category_id BIGINT UNSIGNED NULL, target_scope ENUM('ALL_PUBLIC','WHITELIST','NEW_USER') NOT NULL DEFAULT 'ALL_PUBLIC', whitelisted_users JSON NULL, city_zone VARCHAR(128) NULL, venue_name VARCHAR(255) NULL, gps_mode ENUM('GPS_REQUIRED','DESK_STUDY') NOT NULL DEFAULT 'GPS_REQUIRED', latitude DECIMAL(10,7) NOT NULL DEFAULT 0, longitude DECIMAL(10,7) NOT NULL DEFAULT 0, proximity_alert_radius INT UNSIGNED NOT NULL DEFAULT 30, scanner_unlock_radius INT UNSIGNED NOT NULL DEFAULT 20, indoor_micro_clue TEXT NULL, reward_type ENUM('PROMO_CASH','COUPON_VOUCHER','DIRECT_CASH','MILESTONE') NOT NULL DEFAULT 'PROMO_CASH', reward_amount DECIMAL(18,2) NOT NULL DEFAULT 15, min_cart_value DECIMAL(18,2) NOT NULL DEFAULT 300, ttl_minutes INT UNSIGNED NOT NULL DEFAULT 30, auto_reversal TINYINT(1) NOT NULL DEFAULT 1, max_budget_scans INT UNSIGNED NOT NULL DEFAULT 500, scan_frequency_policy ENUM('PER_DEVICE','SINGLE_USE','DAILY','POOL') NOT NULL DEFAULT 'PER_DEVICE', is_active TINYINT(1) NOT NULL DEFAULT 1, created_by INT UNSIGNED NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_spot_active(is_active,category_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS riddle_pool (riddle_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, spot_id VARCHAR(64) NOT NULL, riddle_text TEXT NOT NULL, primary_answer VARCHAR(128) NOT NULL, synonyms JSON NOT NULL, yt_video_id VARCHAR(32) NULL, weight_percentage INT UNSIGNED NOT NULL DEFAULT 100, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_riddle_spot(spot_id,weight_percentage), FOREIGN KEY(spot_id) REFERENCES spot_campaigns(spot_id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS scan_audit_ledger (audit_id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, device_hash VARCHAR(128) NOT NULL, user_id BIGINT UNSIGNED NOT NULL, spot_id VARCHAR(64) NOT NULL, riddle_id BIGINT UNSIGNED NULL, user_input_answer TEXT NULL, is_correct TINYINT(1) NOT NULL DEFAULT 0, attempt_count INT UNSIGNED NOT NULL DEFAULT 1, gps_lat_submitted DECIMAL(10,7) NULL, gps_lng_submitted DECIMAL(10,7) NULL, distance_calculated_m DECIMAL(12,2) NULL, status ENUM('PASS','WRONG_ATTEMPT','BLOCKED_DEVICE','EXHAUSTED','EXPIRED','SETTLED') NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, INDEX idx_scan_audit_spot(spot_id,created_at), INDEX idx_scan_device(device_hash,spot_id)) ENGINE=InnoDB;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='logo_path'),'ALTER TABLE vendors ADD COLUMN logo_path VARCHAR(255) NULL AFTER address','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='vendors') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='vendors' AND column_name='cover_image_path'),'ALTER TABLE vendors ADD COLUMN cover_image_path VARCHAR(255) NULL AFTER logo_path','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
SET @sql := (SELECT IF(EXISTS(SELECT 1 FROM information_schema.tables WHERE table_schema=@db AND table_name='spot_campaigns') AND NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=@db AND table_name='spot_campaigns' AND column_name='gps_mode'),'ALTER TABLE spot_campaigns ADD COLUMN gps_mode ENUM(''GPS_REQUIRED'',''DESK_STUDY'') NOT NULL DEFAULT ''GPS_REQUIRED'' AFTER venue_name','SELECT 1')); PREPARE s FROM @sql; EXECUTE s; DEALLOCATE PREPARE s;
INSERT IGNORE INTO system_settings(`key`,`value`,is_secret) VALUES ('brand_name','Hunter Wallet',0),('brand_tagline','Secure administration portal',0),('theme_mode','light',0),('primary_color','#12304a',0),('accent_color','#24c79a',0),('default_currency','INR',0),('smtp_port','587',0),('session_timeout','1800',0);
