<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
if(PHP_SAPI!=='cli')exit("CLI only\n");
$pdo=db();$admin=(int)$pdo->query('SELECT id FROM admins ORDER BY id LIMIT 1')->fetchColumn();if(!$admin)exit("Create an admin first: php database/create_admin.php ...\n");
$pdo->beginTransaction();
try{
 $find=function(string $sql,array $p=[]){global $pdo;$s=$pdo->prepare($sql);$s->execute($p);return $s->fetchColumn();};
 $user=function(string $name,string $mobile,string $email)use($pdo,$find){$id=$find('SELECT id FROM users WHERE mobile=?',[$mobile]);if(!$id){$pdo->prepare('INSERT INTO users(name,mobile,email,password_hash,status,is_verified) VALUES(?,?,?,? ,"ACTIVE",1)')->execute([$name,$mobile,$email,password_hash('DemoUser123!',PASSWORD_DEFAULT)]);$id=(int)$pdo->lastInsertId();}$pdo->prepare('INSERT IGNORE INTO wallets(user_id,balance,bonus_balance,promo_balance,status) VALUES(?,100,25,15,"ACTIVE")')->execute([$id]);$pdo->prepare('INSERT IGNORE INTO user_devices(user_id,device_id,device_name,platform,status,last_active_at) VALUES(?,?,?,"Android","ACTIVE",NOW())')->execute([$id,'demo-device-'.$id,'Demo device']);return (int)$id;};
 $u1=$user('Aarav Sharma','9000000001','aarav.demo@example.test');$u2=$user('Sara Khan','9000000002','sara.demo@example.test');$u3=$user('Demo Customer','9000000003','customer.demo@example.test');
 $cat=function(string $name,string $slug,string $character,int $limit)use($pdo,$find,$admin){$id=$find('SELECT id FROM video_categories WHERE slug=?',[$slug]);if(!$id){$pdo->prepare('INSERT INTO video_categories(name,slug,character_name,channel_url,teaser_video_id,broadcast_message,capacity_limit,status,created_by) VALUES(?,?,?,?,?,?,?,"ACTIVE",?)')->execute([$name,$slug,$character,'https://youtube.com/@HunterWalletRetail','demo_teaser_v1','Demo notice: hidden reward spots are live!', $limit,$admin]);$id=$pdo->lastInsertId();}return (int)$id;};
 $mall=$cat('Shopping Mall & Retail Hunt','shopping-mall','Shopping Robot Mascot',1000);$zoo=$cat('Patna Zoo & Wildlife Safari','patna-zoo','Zoo Explorer Mascot',500);$recharge=$cat('Mobile Recharge & Utility Deals','recharge','Recharge Lightning Mascot',2000);
 $hunt=$find('SELECT id FROM hunts WHERE slug=?',['demo-city-hunt']);if(!$hunt){$pdo->prepare('INSERT INTO hunts(title,slug,description,rules,start_at,end_at,activation_fee,reward_min,reward_max,status,created_by) VALUES(?,?,?, ?,DATE_SUB(NOW(),INTERVAL 1 DAY),DATE_ADD(NOW(),INTERVAL 30 DAY),0,15,500,"ACTIVE",?)')->execute(['Demo City Treasure Hunt','demo-city-hunt','Seeded campaign for testing the complete admin workflow.','One scan per device.',$admin]);$hunt=(int)$pdo->lastInsertId();}else $hunt=(int)$hunt;
 $loc=$find('SELECT id FROM hunt_locations WHERE hunt_id=? AND name=?',[$hunt,'Patna Central Mall - Lift Lobby']);if(!$loc){$pdo->prepare('INSERT INTO hunt_locations(hunt_id,name,address,latitude,longitude,radius_meters,status) VALUES(?,?,?,25.612045,85.144021,100,"ACTIVE")')->execute([$hunt,'Patna Central Mall - Lift Lobby','Fraser Road, Patna']);$loc=(int)$pdo->lastInsertId();}else $loc=(int)$loc;
 $token=bin2hex(random_bytes(32));$qr=$find('SELECT id FROM hunt_qr_codes WHERE label=?', ['DEMO-MALL-001']);if(!$qr){$pdo->prepare('INSERT INTO hunt_qr_codes(hunt_id,location_id,token_hash,label,status,max_scans,created_by) VALUES(?,?,?, ?,"ACTIVE",500,?)')->execute([$hunt,$loc,hash('sha256',$token),'DEMO-MALL-001',$admin]);$qr=(int)$pdo->lastInsertId();}else $qr=(int)$qr;
 if(!$find('SELECT id FROM hunt_user_activations WHERE user_id=? AND hunt_id=?',[$u1,$hunt]))$pdo->prepare('INSERT INTO hunt_user_activations(user_id,hunt_id,activation_type,status,activated_by,expires_at) VALUES(?,?,"ADMIN","ACTIVE",?,DATE_ADD(NOW(),INTERVAL 30 DAY))')->execute([$u1,$hunt,$admin]);
 if(!$find('SELECT id FROM qr_campaigns WHERE campaign_code=?',['DEMO-CAMPAIGN']))$pdo->prepare('INSERT INTO qr_campaigns(campaign_code,name,category_id,qr_code_id,clue_text,geofence_enabled,reward_type,reward_value,ttl_minutes,auto_reversal_enabled,scan_frequency,budget_limit,status,created_by) VALUES("DEMO-CAMPAIGN","Demo Mall Reward",?,?,"Find the red pillar",1,"PROMO_CASH",15,30,1,"PER_DEVICE",500,"ACTIVE",?)')->execute([$mall,$qr,$admin]);
 $vendor=$find('SELECT id FROM vendors WHERE vendor_code=?',['DEMO-VENDOR']);if(!$vendor){$pdo->prepare('INSERT INTO vendors(vendor_code,name,shop_name,email,mobile,address,kyc_status,status,created_by) VALUES("DEMO-VENDOR","Demo Merchant","Demo Retail Counter","merchant.demo@example.test","9000000099","Patna Central Mall","APPROVED","ACTIVE",?)')->execute([$admin]);$vendor=(int)$pdo->lastInsertId();}
 if(!$find('SELECT id FROM coupons WHERE code_reference=?',['DEMO-COUPON']))$pdo->prepare('INSERT INTO coupons(code_hash,code_reference,title,discount_amount,min_cart_amount,merchant_id,ttl_minutes,expires_at,status,user_id,created_by) VALUES(?,"DEMO-COUPON","Demo ₹100 off",100,300,?,30,DATE_ADD(NOW(),INTERVAL 30 DAY),"ACTIVE",?,?)')->execute([hash('sha256','DEMO100'),$vendor,$u1,$admin]);
 $pdo->prepare('INSERT INTO notifications(user_id,type,channel,title,message,status) VALUES(?,"DEMO","IN_APP","Welcome to Hunter Wallet","Your demo wallet and campaign are ready.","QUEUED")')->execute([$u1]);
 if($find("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name='spot_campaigns'")){$spot='DEMO_SPOT_MALL_001';if(!$find('SELECT spot_id FROM spot_campaigns WHERE spot_id=?',[$spot])){$master=bin2hex(random_bytes(32));$pdo->prepare('INSERT INTO spot_campaigns(spot_id,master_token_hash,spot_name,category_id,target_scope,whitelisted_users,city_zone,venue_name,latitude,longitude,proximity_alert_radius,scanner_unlock_radius,indoor_micro_clue,reward_type,reward_amount,min_cart_value,ttl_minutes,auto_reversal,max_budget_scans,scan_frequency_policy,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$spot,hash('sha256',$master),'Demo Mall Lift Lobby',$mall,'ALL_PUBLIC','[]','Patna','Demo Mall',25.612045,85.144021,30,20,'First floor → red pillar','PROMO_CASH',15,300,30,1,500,'PER_DEVICE',$admin]);$pdo->prepare('INSERT INTO riddle_pool(spot_id,riddle_text,primary_answer,synonyms,yt_video_id) VALUES(?,?,?,?,?)')->execute([$spot,'Mujhe pehno toh waqt rukta nahi, main kaun?','Ghadi',json_encode(['watch','clock','samay']),'dQw4w9WgXcQ']);}}
 $pdo->commit();echo "Demo data seeded successfully.\nUsers: 9000000001, 9000000002, 9000000003\nDemo coupon: DEMO100\n";
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();fwrite(STDERR,"Seed failed: ".$e->getMessage()."\n");exit(1);}
