<?php
declare(strict_types=1);
require dirname(__DIR__).'/includes/bootstrap.php';
require_permission('dashboard.view');
$pdo=db();
$q=trim((string)input('q'));$module=strtolower(trim((string)input('module')));$from=(string)input('from',date('Y-m-01'));$to=(string)input('to',date('Y-m-d'));
$where=[];$params=[];if($q!==''){$where[]='(v.vendor_code LIKE ? OR v.name LIKE ? OR v.shop_name LIKE ?)';$params=['%'.$q.'%','%'.$q.'%','%'.$q.'%'];}
$stmt=$pdo->prepare('SELECT v.id,v.vendor_code,v.name,v.shop_name,v.business_category,v.commission_rate,v.kyc_status,v.status FROM vendors v'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY v.id DESC LIMIT 100');$stmt->execute($params);$vendors=$stmt->fetchAll();
if($module!==''&&$module!=='vendors')$vendors=[];
$stats=$pdo->query("SELECT COUNT(*) total_vendors,COALESCE(SUM(kyc_status='PENDING'),0) pending_kyc FROM vendors")->fetch();
$money=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM withdrawals WHERE requested_at>=? AND requested_at<DATE_ADD(?,INTERVAL 1 DAY) AND status IN ('PENDING','UNDER_REVIEW','APPROVED','PROCESSING','PAID')");$money->execute([$from,$to]);$withdrawalTotal=$money->fetchColumn();
$requests=$pdo->prepare("SELECT COALESCE(SUM(amount),0) FROM wallet_transactions WHERE created_at>=? AND created_at<DATE_ADD(?,INTERVAL 1 DAY) AND type IN ('CREDIT','DEBIT','WITHDRAWAL') AND status IN ('SUCCESS','PENDING')");$requests->execute([$from,$to]);$moneyRequested=$requests->fetchColumn();
$pageTitle='Master dashboard';$pageSubtitle='Unified vendor, finance and moderation analytics';require APP_ROOT.'/includes/header.php';
?>
<style>.dashboard-metrics .card{border-left:4px solid #2d6cdf}.dashboard-metrics .metric-yellow{border-color:#e0a800;background:#fff8d8}.dashboard-metrics .metric-cyan{border-color:#16a9cf;background:#e5f8ff}.dashboard-metrics .metric-green{border-color:#1aa36f;background:#e5fff2}.dashboard-metrics .metric-purple{border-color:#9b51e0;background:#f8edff}.dashboard-metrics .metric-red{border-color:#e04b64;background:#fff0f2}</style>
<section class="vendor-hero"><h2>HUNTER WALLET · MASTER ALL-IN-ONE DASHBOARD &amp; ANALYTICS PANEL</h2><span>Unified administrative dashboard tracking vendors, financial requests and product approvals</span></section>
<section class="panel"><h2>1. Master live metrics overview</h2><div class="grid stats dashboard-metrics"><?php foreach([['Total vendors',$stats['total_vendors'],'metric-blue'],['Pending verification',str_pad((string)$stats['pending_kyc'],2,'0',STR_PAD_LEFT),'metric-yellow'],['Total money requests',money($moneyRequested),'metric-cyan'],['Total withdrawals',money($withdrawalTotal),'metric-green'],['Products approved','—','metric-purple'],['Products pending','—','metric-red']] as $card):?><div class="card <?=e($card[2])?>"><span class="label"><?=e($card[0])?></span><span class="value"><?=e($card[1])?></span></div><?php endforeach?></div></section>
<section class="panel"><h2>2. Search, date filter &amp; control bar</h2><form class="filters" method="get"><input name="q" value="<?=e($q)?>" placeholder="Vendor name / product ID"><select name="module"><option value="">All modules</option><option value="vendors" <?=$module==='vendors'?'selected':''?>>Vendors</option><option value="finance" <?=$module==='finance'?'selected':''?>>Finance</option><option value="products" <?=$module==='products'?'selected':''?>>Products</option></select><label>From <input type="date" name="from" value="<?=e($from)?>"></label><label>To <input type="date" name="to" value="<?=e($to)?>"></label><button class="btn">Apply filter</button></form></section>
<section class="panel"><div class="panel-head"><h2>3. Part A: New vendors &amp; verification overview</h2><a class="btn secondary" href="<?=e(app_url('/admin/vendors/dashboard.php'))?>">Vendor dashboard</a></div><div class="table-wrap"><table><thead><tr><th>Vendor ID</th><th>Business name &amp; category</th><th>Commission setting</th><th>Money requested / payout</th><th>KYC / verification</th><th>Account status</th><th>Admin controls</th></tr></thead><tbody><?php foreach($vendors as $v):?><tr><td><?=e($v['vendor_code'])?></td><td><?=e($v['shop_name'])?><br><small><?=e($v['business_category']??'—')?></small></td><td><?=e($v['commission_rate']??'Default')?>%</td><td>—</td><td><span class="badge <?=strtolower(e($v['kyc_status']))?>"><?=e($v['kyc_status'])?></span></td><td><span class="badge <?=strtolower(e($v['status']))?>"><?=e($v['status'])?></span></td><td><a href="<?=e(app_url('/admin/vendors/index.php'))?>">View directory</a></td></tr><?php endforeach?></tbody></table><?php if(!$vendors):?><div class="empty">No vendors match the selected filters.</div><?php endif?></div></section>
<section class="panel"><div class="panel-head"><h2>4. Part B: Products &amp; courses approval overview</h2><span class="help">Product approval workflow is not configured in this installation.</span></div><div class="empty">No product/course approval records are available yet. Add the product workflow tables before enabling approve/reject actions.</div></section>
<section class="panel"><h2>Unified dashboard execution &amp; filtering logic</h2><p class="help">Metrics use live vendor, wallet and withdrawal records for the selected date range. Vendor search filters the verification table. Product metrics remain unavailable until a product approval workflow is installed.</p></section>
<?php require APP_ROOT.'/includes/footer.php';
