<?php declare(strict_types=1); require dirname(__DIR__,2).'/includes/bootstrap.php'; require_permission('users.view');
if(is_post()){require_permission('users.edit');verify_csrf();try{$name=trim((string)input('name'));$mobile=trim((string)input('mobile'));$email=filter_var(input('email'),FILTER_VALIDATE_EMAIL);$password=(string)input('password');if($name===''||!preg_match('/^[0-9+() -]{7,30}$/',$mobile)||!$email||strlen($password)<12)throw new InvalidArgumentException('Name, valid email/mobile and a 12+ character password are required.');$pdo=db();$pdo->beginTransaction();$pdo->prepare('INSERT INTO users(name,mobile,email,password_hash,status,is_verified) VALUES(?,?,?,?,"ACTIVE",1)')->execute([$name,$mobile,$email,password_hash($password,PASSWORD_DEFAULT)]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO wallets(user_id,status) VALUES(? ,"ACTIVE")')->execute([$id]);audit_log((int)admin()['id'],'USER_CREATED','users',(string)$id,null,['name'=>$name,'email'=>$email]);$pdo->commit();flash('success','User account and wallet created.');}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof PDOException?'Could not create user. Mobile or email may already exist.':$e->getMessage());}redirect('/admin/users/index.php');}
$q=trim((string)input('q'));$status=strtoupper(trim((string)input('status')));$page=page_int();[$limit,$offset]=pagination($page);$where=[];$params=[];
if($q!==''){$where[]='(CAST(u.id AS CHAR)=? OR u.name LIKE ? OR u.email LIKE ? OR u.mobile LIKE ?)';$params[]=ltrim($q,'#');$params=array_merge($params,array_fill(0,3,'%'.$q.'%'));}
if(in_array($status,['ACTIVE','BLOCKED','SUSPENDED','PENDING'],true)){$where[]='u.status=?';$params[]=$status;}$sqlWhere=$where?' WHERE '.implode(' AND ',$where):'';
$count=db()->prepare('SELECT COUNT(*) FROM users u'.$sqlWhere);$count->execute($params);$total=(int)$count->fetchColumn();
$stmt=db()->prepare('SELECT u.*,w.balance,w.currency,(SELECT device_name FROM user_devices WHERE user_id=u.id ORDER BY last_active_at DESC LIMIT 1) device FROM users u LEFT JOIN wallets w ON w.user_id=u.id'.$sqlWhere.' ORDER BY u.id DESC LIMIT '.$limit.' OFFSET '.$offset);$stmt->execute($params);$users=$stmt->fetchAll();
$pageTitle='Users';$pageSubtitle='Search, review and control customer accounts';require APP_ROOT.'/includes/header.php';?>
<?php if(can('users.edit')):?><section class="panel"><div class="panel-head"><h2>Add customer</h2><span class="help">Creates an active account and wallet</span></div><form method="post" class="form-grid"><?=csrf_field()?><div class="field"><label>Name</label><input name="name" required maxlength="120"></div><div class="field"><label>Mobile</label><input name="mobile" required></div><div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field"><label>Temporary password</label><input type="password" name="password" minlength="12" autocomplete="new-password" required></div><div class="field full"><button class="btn">Create user</button></div></form></section><?php endif?>
<section class="panel"><form class="filters" method="get"><input name="q" value="<?=e($q)?>" placeholder="Search ID, name, email or mobile"><select name="status"><option value="">All statuses</option><?php foreach(['ACTIVE','BLOCKED','SUSPENDED','PENDING'] as $s):?><option <?=$status===$s?'selected':''?>><?=e($s)?></option><?php endforeach?></select><button class="btn">Apply filters</button></form><div class="table-wrap"><table><thead><tr><th>ID</th><th>User</th><th>Mobile</th><th>Status</th><th>Balance</th><th>Risk</th><th>Device</th><th>Created</th><th></th></tr></thead><tbody><?php foreach($users as $u):?><tr><td>#<?=e($u['id'])?></td><td><strong><?=e($u['name'])?></strong><br><small><?=e($u['email']??'—')?></small></td><td><?=e($u['mobile'])?></td><td><span class="badge <?=strtolower(e($u['status']))?>"><?=e($u['status'])?></span></td><td><?=money($u['balance']??0)?></td><td><span class="risk <?=strtolower(e($u['risk_level']))?>"><?=e($u['risk_level'])?></span></td><td><?=e($u['device']??'—')?></td><td><?=e($u['created_at'])?></td><td><a class="btn small secondary" href="<?=e(app_url('/admin/users/view.php?id='.$u['id']))?>">View</a></td></tr><?php endforeach?></tbody></table><?php if(!$users):?><div class="empty">No users match these filters.</div><?php endif?></div><div class="pagination"><?php for($i=1;$i<=ceil($total/$limit);$i++):?><a href="?<?=e(http_build_query(['q'=>$q,'status'=>$status,'page'=>$i]))?>"><?=$i?></a><?php endfor?></div></section><?php require APP_ROOT.'/includes/footer.php';
