<?php
declare(strict_types=1);

function vendor_user(): ?array
{
    static $cached=false;if($cached!==false)return $cached;if(empty($_SESSION['vendor_user_id'])||empty($_SESSION['vendor_session_token']))return $cached=null;$hash=hash('sha256',$_SESSION['vendor_session_token']);$s=db()->prepare("SELECT vu.*,v.name vendor_name,v.shop_name,v.vendor_code,v.status vendor_status FROM vendor_sessions vs JOIN vendor_users vu ON vu.id=vs.vendor_user_id JOIN vendors v ON v.id=vu.vendor_id WHERE vs.vendor_user_id=? AND vs.php_session_hash=? AND vs.revoked_at IS NULL AND vs.expires_at>NOW() AND vu.status='ACTIVE' AND v.status='ACTIVE'");$s->execute([$_SESSION['vendor_user_id'],$hash]);return $cached=$s->fetch()?:null;
}
function require_vendor(): void { if(!vendor_user()){flash('error','Please sign in as a vendor.');redirect('/vendor/login.php');} }
function attempt_vendor_login(string $identity,string $password): bool
{
    $hash=hash('sha256',strtolower($identity));$r=db()->prepare('SELECT COUNT(*) FROM vendor_login_attempts WHERE (identity_hash=? OR ip_address=?) AND successful=0 AND attempted_at>DATE_SUB(NOW(),INTERVAL 15 MINUTE)');$r->execute([$hash,client_ip()]);if((int)$r->fetchColumn()>=5)return false;$s=db()->prepare("SELECT vu.*,v.status vendor_status FROM vendor_users vu JOIN vendors v ON v.id=vu.vendor_id WHERE (vu.username=? OR vu.email=?) LIMIT 1");$s->execute([$identity,$identity]);$u=$s->fetch();$ok=$u&&$u['status']==='ACTIVE'&&$u['vendor_status']==='ACTIVE'&&password_verify($password,$u['password_hash']);db()->prepare('INSERT INTO vendor_login_attempts(identity_hash,ip_address,successful) VALUES(?,?,?)')->execute([$hash,client_ip(),$ok?1:0]);if(!$ok){log_security(null,'VENDOR_LOGIN_FAILED','MEDIUM','Failed vendor login',['identity_hash'=>$hash]);return false;}session_regenerate_id(true);$token=bin2hex(random_bytes(32));$_SESSION['vendor_user_id']=(int)$u['id'];$_SESSION['vendor_session_token']=$token;$_SESSION['last_activity']=time();db()->prepare('INSERT INTO vendor_sessions(vendor_user_id,php_session_hash,ip_address,expires_at) VALUES(?,?,?,DATE_ADD(NOW(),INTERVAL 8 HOUR))')->execute([$u['id'],hash('sha256',$token),client_ip()]);db()->prepare('UPDATE vendor_users SET last_login_at=NOW(),last_login_ip=? WHERE id=?')->execute([client_ip(),$u['id']]);audit_log(null,'VENDOR_LOGIN','vendor_auth',(string)$u['id']);return true;
}
function redeem_gift_code(array $vendor,string $plainCode): array
{
    $clean=strtoupper(trim($plainCode));$hash=hash('sha256',$clean);$pdo=db();$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT rc.*,g.name gift_name,g.status gift_status,g.total_quantity,g.redeemed_quantity,g.valid_from,g.valid_until FROM reward_codes rc JOIN gifts g ON g.id=rc.gift_id WHERE rc.code_hash=? FOR UPDATE');$q->execute([$hash]);$code=$q->fetch();$reason=null;if(!$code)$reason='Code not found.';elseif($code['status']!=='ACTIVE')$reason='Code is not active.';elseif($code['expires_at']&&$code['expires_at']<date('Y-m-d H:i:s'))$reason='Code has expired.';elseif($code['gift_status']!=='ACTIVE'||($code['valid_from']&&$code['valid_from']>date('Y-m-d H:i:s'))||($code['valid_until']&&$code['valid_until']<date('Y-m-d H:i:s')))$reason='Gift campaign is not active.';elseif((int)$code['redeemed_quantity']>=(int)$code['total_quantity'])$reason='Gift inventory is exhausted.';
        if($reason){$pdo->rollBack();db()->prepare('INSERT INTO gift_redemption_attempts(vendor_id,vendor_user_id,code_reference,code_hash,ip_address,result,reason) VALUES(?,?,?,?,?,"REJECTED",?)')->execute([$vendor['vendor_id'],$vendor['id'],$code['code_reference']??null,$hash,client_ip(),$reason]);log_security((int)($code['user_id']??0)?:null,'GIFT_REDEMPTION_REJECTED','MEDIUM',$reason,['vendor_id'=>$vendor['vendor_id']]);throw new RuntimeException($reason);}
        $redemption=transaction_code('RED');$pdo->prepare('INSERT INTO gift_redemptions(redemption_id,reward_code_id,gift_id,user_id,vendor_id,vendor_user_id) VALUES(?,?,?,?,?,?)')->execute([$redemption,$code['id'],$code['gift_id'],$code['user_id'],$vendor['vendor_id'],$vendor['id']]);$updatedCode=$pdo->prepare("UPDATE reward_codes SET status='REDEEMED',redeemed_at=NOW() WHERE id=? AND status='ACTIVE'");$updatedCode->execute([$code['id']]);if($updatedCode->rowCount()!==1)throw new RuntimeException('Code was already redeemed.');$inventory=$pdo->prepare('UPDATE gifts SET redeemed_quantity=redeemed_quantity+1 WHERE id=? AND redeemed_quantity<total_quantity');$inventory->execute([$code['gift_id']]);if($inventory->rowCount()!==1)throw new RuntimeException('Could not reserve gift inventory.');$pdo->prepare('INSERT INTO gift_redemption_attempts(vendor_id,vendor_user_id,code_reference,code_hash,ip_address,result,reason) VALUES(?,?,?,?,?,"REDEEMED",NULL)')->execute([$vendor['vendor_id'],$vendor['id'],$code['code_reference'],$hash,client_ip()]);audit_log(null,'GIFT_REDEEMED','vendor_redemptions',$redemption,null,['vendor_id'=>$vendor['vendor_id'],'user_id'=>$code['user_id'],'gift_id'=>$code['gift_id']]);$pdo->commit();return ['redemption_id'=>$redemption,'gift'=>$code['gift_name'],'code_reference'=>$code['code_reference']];
    }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
}
