<?php
declare(strict_types=1);require dirname(__DIR__,2).'/includes/bootstrap.php';require_permission('admins.edit');
$id=filter_var(input('id'),FILTER_VALIDATE_INT);if(!$id){http_response_code(404);exit('Not found');}
$stmt=db()->prepare('SELECT id,role_id,name,username,email,status,mfa_enabled FROM admins WHERE id=?');$stmt->execute([$id]);$account=$stmt->fetch();if(!$account){http_response_code(404);exit('Not found');}$roles=db()->query('SELECT * FROM admin_roles ORDER BY id')->fetchAll();
if(is_post()){
    verify_csrf();$name=trim((string)input('name'));$email=filter_var(input('email'),FILTER_VALIDATE_EMAIL);$role=(int)input('role_id');$status=strtoupper((string)input('status'));$password=(string)input('password');
    if($id===(int)admin()['id']&&$status!=='ACTIVE')flash('error','You cannot block your own active session.');elseif(!$name||!$email||!in_array($status,['ACTIVE','BLOCKED'],true)||($password!==''&&strlen($password)<12))flash('error','Enter valid administrator details.');else{
        $pdo=db();$pdo->beginTransaction();try{$roleStmt=$pdo->prepare('SELECT id FROM admin_roles WHERE id=?');$roleStmt->execute([$role]);if(!$roleStmt->fetch())throw new RuntimeException('Invalid role.');$sql='UPDATE admins SET name=?,email=?,role_id=?,status=?,updated_at=NOW()';$params=[$name,$email,$role,$status];if($password!==''){$sql.=',password_hash=?';$params[]=password_hash($password,PASSWORD_DEFAULT);}$sql.=' WHERE id=?';$params[]=$id;$pdo->prepare($sql)->execute($params);audit_log((int)admin()['id'],'ADMIN_UPDATED','admins',(string)$id,$account,['name'=>$name,'email'=>$email,'role_id'=>$role,'status'=>$status,'password_changed'=>$password!=='']);$pdo->commit();flash('success','Administrator updated.');redirect('/admin/admins/index.php');}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof PDOException?'Could not update administrator. Email may already exist.':$e->getMessage());}
    }
}
$pageTitle='Edit administrator';require APP_ROOT.'/includes/header.php';?>
<section class="panel"><form method="post" class="form-grid"><?=csrf_field()?><div class="field"><label>Name</label><input name="name" value="<?=e($account['name'])?>" maxlength="120" required></div><div class="field"><label>Email</label><input name="email" type="email" value="<?=e($account['email'])?>" maxlength="190" required></div><div class="field"><label>Role</label><select name="role_id"><?php foreach($roles as $r):?><option value="<?=e($r['id'])?>" <?=$r['id']==$account['role_id']?'selected':''?>><?=e($r['name'])?></option><?php endforeach?></select></div><div class="field"><label>Status</label><select name="status"><option <?=$account['status']==='ACTIVE'?'selected':''?>>ACTIVE</option><option <?=$account['status']==='BLOCKED'?'selected':''?>>BLOCKED</option></select></div><div class="field full"><label>New password</label><input name="password" type="password" minlength="12" autocomplete="new-password"><small class="help">Leave blank to keep the existing password.</small></div><div class="field full"><button class="btn">Save administrator</button></div></form></section><?php require APP_ROOT.'/includes/footer.php';
