<?php
declare(strict_types=1); require dirname(__DIR__,2).'/includes/bootstrap.php'; require_admin();
if ((admin()['role_name'] ?? '') !== 'Super Admin') { http_response_code(403); exit('Only Super Admin can manage roles.'); }
if (is_post()) { verify_csrf(); $action=input('action'); $id=(int)input('role_id'); $name=trim((string)input('name')); $pdo=db(); try { $pdo->beginTransaction();
    if ($action==='create') { if (!preg_match('/^[A-Za-z][A-Za-z0-9 _-]{2,79}$/',$name)) throw new RuntimeException('Role name must be 3-80 characters.'); $pdo->prepare('INSERT INTO admin_roles(name) VALUES(?)')->execute([$name]); $id=(int)$pdo->lastInsertId(); }
    elseif ($action==='rename') { if ($id<1 || $name==='') throw new RuntimeException('Invalid role.'); $q=$pdo->prepare('SELECT name FROM admin_roles WHERE id=?');$q->execute([$id]);if(($q->fetchColumn()??'')==='Super Admin')throw new RuntimeException('Super Admin cannot be renamed.');$pdo->prepare('UPDATE admin_roles SET name=? WHERE id=?')->execute([$name,$id]); }
    elseif ($action==='delete') { $q=$pdo->prepare('SELECT name FROM admin_roles WHERE id=?');$q->execute([$id]);$role=$q->fetch();if(!$role||$role['name']==='Super Admin')throw new RuntimeException('This role cannot be deleted.');$q=$pdo->prepare('SELECT COUNT(*) FROM admins WHERE role_id=?');$q->execute([$id]);if((int)$q->fetchColumn()>0)throw new RuntimeException('Reassign administrators before deleting this role.');$pdo->prepare('DELETE FROM admin_role_permissions WHERE role_id=?')->execute([$id]);$pdo->prepare('DELETE FROM admin_roles WHERE id=?')->execute([$id]); }
    else throw new RuntimeException('Unknown role action.'); audit_log((int)admin()['id'],'ROLE_CHANGED','admin_roles',(string)$id,null,['action'=>$action,'name'=>$name]); $pdo->commit(); flash('success','Role updated.');
} catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e instanceof PDOException?'Role name already exists.':$e->getMessage());} redirect('/admin/admins/roles.php'); }
$roles=db()->query('SELECT r.*,COUNT(rp.permission_id) permission_count,COUNT(DISTINCT a.id) admin_count FROM admin_roles r LEFT JOIN admin_role_permissions rp ON rp.role_id=r.id LEFT JOIN admins a ON a.role_id=r.id GROUP BY r.id ORDER BY r.id')->fetchAll();$pageTitle='Role permissions';$pageSubtitle='Super Admin controlled access profiles';require APP_ROOT.'/includes/header.php';
?><section class="panel"><h2>Create role</h2><form method="post" class="form-grid"><?=csrf_field()?><input type="hidden" name="action" value="create"><div class="field"><label>Role name</label><input name="name" maxlength="80" required placeholder="Operations Manager"></div><div class="field"><button class="btn" type="submit">Add role</button></div></form></section>
<section class="panel"><div class="table-wrap"><table><thead><tr><th>Role</th><th>Permissions</th><th>Administrators</th><th>Actions</th></tr></thead><tbody><?php foreach($roles as $role):?><tr><td><strong><?=e($role['name'])?></strong></td><td><?=$role['name']==='Super Admin'?'All':(int)$role['permission_count']?></td><td><?=e($role['admin_count'])?></td><td class="actions"><?php if($role['name']!=='Super Admin'):?><form method="post"><?=csrf_field()?><input type="hidden" name="action" value="rename"><input type="hidden" name="role_id" value="<?=e($role['id'])?>"><input name="name" value="<?=e($role['name'])?>" maxlength="80"><button class="btn small secondary">Rename</button></form><a class="btn small secondary" href="<?=e(app_url('/admin/admins/permissions.php?role_id='.$role['id']))?>">Permissions</a><form method="post" data-confirm="Delete this role?"><?=csrf_field()?><input type="hidden" name="action" value="delete"><input type="hidden" name="role_id" value="<?=e($role['id'])?>"><button class="btn small danger">Delete</button></form><?php else:?><span class="badge active">Full access</span><?php endif?></td></tr><?php endforeach?></tbody></table></div></section><?php require APP_ROOT.'/includes/footer.php';
