<?php
declare(strict_types=1);
require dirname(__DIR__,2).'/includes/bootstrap.php';
require_permission('vendors.view');
$pdo=db(); $id=(int)input('id'); if($id<1) redirect('/admin/vendors/index.php');

$load=function()use($pdo,$id){$s=$pdo->prepare('SELECT * FROM vendors WHERE id=?');$s->execute([$id]);return $s->fetch();};
if (input('download_qr')==='1') {
    require_permission('vendors.manage'); $v=$load();
    if (!$v || trim((string)($v['vendor_qr_payload']??''))==='') { http_response_code(404); exit('QR payload unavailable until vendor verification is complete.'); }
    audit_log((int)admin()['id'],'VENDOR_360_QR_DOWNLOADED','vendors',(string)$id);
    header('Content-Type:text/plain; charset=utf-8'); header('Content-Disposition: attachment; filename="'.$v['vendor_code'].'-vendor-qr.txt"'); echo $v['vendor_qr_payload']; exit;
}
if (is_post()) {
    verify_csrf(); require_permission('vendors.manage');
    try {
        $action=strtoupper((string)input('action')); $reason=trim((string)input('reason')); $old=$load(); if(!$old) throw new RuntimeException('Vendor not found.');
        if ($action==='SAVE_PROFILE') {
            $rate=(float)input('commission_rate'); if($rate<0||$rate>100) throw new InvalidArgumentException('Commission must be between 0 and 100%.');
            $rule=trim((string)input('commission_rule')); $notes=trim((string)input('onboarding_notes'));
            $pdo->prepare('UPDATE vendors SET commission_rate=?,commission_rule=?,onboarding_notes=? WHERE id=?')->execute([$rate,$rule?:null,$notes?:null,$id]);
            audit_log((int)admin()['id'],'VENDOR_360_PROFILE_SAVED','vendors',(string)$id,['commission_rate'=>$old['commission_rate'],'commission_rule'=>$old['commission_rule']??null],['commission_rate'=>$rate,'commission_rule'=>$rule]); flash('success','Vendor profile saved.');
        } elseif ($action==='LOGOUT') {
            $pdo->prepare('UPDATE vendor_sessions vs JOIN vendor_users vu ON vu.id=vs.vendor_user_id SET vs.revoked_at=NOW() WHERE vu.vendor_id=? AND vs.revoked_at IS NULL')->execute([$id]); audit_log((int)admin()['id'],'VENDOR_360_LOGOUT','vendors',(string)$id,null,['reason'=>$reason]); flash('success','All vendor sessions revoked.');
        } else {
            $new=['ACTIVATE'=>'ACTIVE','SUSPEND'=>'SUSPENDED','CLOSE'=>'CLOSED'][$action]??null; if(!$new) throw new InvalidArgumentException('Invalid vendor action.'); if($reason==='') throw new InvalidArgumentException('A reason is required.');
            if($action==='ACTIVATE' && (($old['kyc_status']??'')!=='VERIFIED'||($old['bank_verification_status']??'')!=='VERIFIED'||empty($old['identity_proof_path'])||empty($old['address_proof_path'])||empty($old['cancelled_cheque_path'])||empty($old['bank_account_number'])||empty($old['bank_ifsc'])||(float)$old['commission_rate']<=0)) throw new InvalidArgumentException('Activation blocked: verified KYC, bank details, documents and commission are required.');
            $pdo->prepare('UPDATE vendors SET status=? WHERE id=?')->execute([$new,$id]); audit_log((int)admin()['id'],'VENDOR_360_'.$action,'vendors',(string)$id,['status'=>$old['status']],['status'=>$new,'reason'=>$reason]); flash('success','Vendor status updated.');
        }
    } catch(Throwable $e){flash('error',$e->getMessage());} redirect('/admin/vendors/profile.php?id='.$id);
}
$vendor=$load(); if(!$vendor) redirect('/admin/vendors/index.php');
$ledgerSql="SELECT settlement_id id,created_at event_date,'ORDER / SETTLEMENT' source,bill_amount gross,promo_amount discount,platform_fee commission,merchant_amount net,status FROM merchant_settlements WHERE merchant_id=? UNION ALL SELECT CONCAT('CLAIM-',id),redeemed_at,'VOUCHER CLAIM',0,0,0,0,'CLAIMED' FROM gift_redemptions WHERE vendor_id=? UNION ALL SELECT CONCAT('WD-',id),requested_at,'VENDOR WITHDRAWAL',amount,0,0,-amount,status FROM vendor_payout_requests WHERE vendor_id=? UNION ALL SELECT CONCAT('ATT-',id),attempted_at,CONCAT('CLAIM ',result),0,0,0,0,COALESCE(reason,result) FROM gift_redemption_attempts WHERE vendor_id=? AND (LOWER(result) LIKE '%reject%' OR LOWER(result) LIKE '%block%' OR LOWER(result) LIKE '%duplicate%' OR LOWER(result) LIKE '%hold%') UNION ALL SELECT request_code,requested_at,'MONEY REQUEST',amount,0,0,amount,status FROM vendor_money_requests WHERE vendor_id=? ORDER BY event_date DESC LIMIT 500";
if (input('export')==='1') { require_permission('vendors.manage'); $q=$pdo->prepare($ledgerSql);$q->execute([$id,$id,$id,$id,$id]); header('Content-Type:text/csv; charset=utf-8'); header('Content-Disposition: attachment; filename="'.$vendor['vendor_code'].'-ledger.csv"'); $out=fopen('php://output','w'); fputcsv($out,['Event ID','Date','Activity / Source','Bill','Discount','Commission','Net Vendor Payout','Status']); while($r=$q->fetch(PDO::FETCH_ASSOC)) fputcsv($out,[$r['id'],$r['event_date'],$r['source'],$r['gross'],$r['discount'],$r['commission'],$r['net'],$r['status']]); fclose($out); audit_log((int)admin()['id'],'VENDOR_360_LEDGER_EXPORTED','vendors',(string)$id,null,['format'=>'csv']); exit; }
$sum=['sales'=>0,'commission'=>0,'settled'=>0,'withdrawn'=>0,'reserved'=>0,'orders'=>0,'claims'=>0,'rejected'=>0];
$q=$pdo->prepare("SELECT COALESCE(SUM(bill_amount),0) sales,COALESCE(SUM(platform_fee),0) commission,COALESCE(SUM(CASE WHEN status='SETTLED' THEN merchant_amount ELSE 0 END),0) settled,COUNT(*) orders FROM merchant_settlements WHERE merchant_id=?");$q->execute([$id]);$sum=array_merge($sum,$q->fetch()?:[]);
$q=$pdo->prepare('SELECT COUNT(*) FROM gift_redemptions WHERE vendor_id=?');$q->execute([$id]);$sum['claims']=(int)$q->fetchColumn(); $sum['orders']+=(int)$sum['claims'];
$q=$pdo->prepare("SELECT COALESCE(SUM(CASE WHEN status='PAID' THEN amount ELSE 0 END),0) withdrawn,COALESCE(SUM(CASE WHEN status IN ('APPROVED','PAID','PROCESSING') THEN amount ELSE 0 END),0) reserved FROM vendor_payout_requests WHERE vendor_id=?");$q->execute([$id]);$sum=array_merge($sum,$q->fetch()?:[]);$q=$pdo->prepare("SELECT COALESCE(SUM(amount),0) requested FROM vendor_money_requests WHERE vendor_id=?");$q->execute([$id]);$sum['requested']=(float)$q->fetchColumn();
$q=$pdo->prepare("SELECT COUNT(*) FROM gift_redemption_attempts WHERE vendor_id=? AND (LOWER(result) LIKE '%reject%' OR LOWER(result) LIKE '%block%' OR LOWER(result) LIKE '%duplicate%' OR LOWER(result) LIKE '%hold%' OR LOWER(reason) LIKE '%reject%' OR LOWER(reason) LIKE '%block%' OR LOWER(reason) LIKE '%duplicate%' OR LOWER(reason) LIKE '%hold%')");$q->execute([$id]);$sum['rejected']=(int)$q->fetchColumn(); $sum['withdrawable']=max(0,(float)$sum['settled']-(float)$sum['reserved']);
$q=$pdo->prepare($ledgerSql);$q->execute([$id,$id,$id,$id,$id]);$ledger=$q->fetchAll();
$q=$pdo->prepare("SELECT id,action,module,record_id,old_data,new_data,admin_id,ip_address,created_at FROM audit_logs WHERE module='vendors' AND record_id=? ORDER BY id DESC LIMIT 100");$q->execute([(string)$id]);$audits=$q->fetchAll();
$pageTitle='Vendor 360° master profile';$pageSubtitle='Inspection, financial ledger and controlled account actions';require APP_ROOT.'/includes/header.php';
?>
<section class="panel"><div class="panel-head"><div><h2><?=e($vendor['vendor_code'])?> · <?=e($vendor['shop_name'])?></h2><p class="help"><?=e($vendor['business_category']??'—')?> · Owner: <?=e($vendor['owner_name']??$vendor['name'])?> · <?=e(number_format((float)$vendor['commission_rate'],2))?>% commission</p></div><span class="badge <?=strtolower(e($vendor['status']))?>"><?=e($vendor['status'])?></span></div><div class="grid stats"><div class="card"><span class="label">Withdrawable balance</span><span class="value"><?=money($sum['withdrawable'])?></span></div><div class="card"><span class="label">Platform commission paid</span><span class="value"><?=money($sum['commission'])?></span></div><div class="card"><span class="label">Orders / redemptions</span><span class="value"><?=e($sum['orders'])?></span></div><div class="card"><span class="label">Rejected / held claims</span><span class="value"><?=e($sum['rejected'])?></span></div><div class="card"><span class="label">Money requested</span><span class="value"><?=money($sum['requested'])?></span></div><div class="card"><span class="label">Withdrawals done</span><span class="value"><?=money($sum['withdrawn'])?></span></div><div class="card"><span class="label">Lifetime gross sales</span><span class="value"><?=money($sum['sales'])?></span></div></div><div class="actions"><a class="btn secondary" href="?id=<?=$id?>&amp;export=1">Export full vendor ledger CSV</a><?php if(can('vendors.manage')):?><a class="btn secondary" href="?id=<?=$id?>&amp;download_qr=1">Download vendor QR payload</a><form method="post" class="actions"><?=csrf_field()?><input type="hidden" name="action" value="LOGOUT"><button class="btn secondary">Force logout POS/devices</button></form><button class="btn" onclick="control.showModal()">Account controls</button><?php endif?></div></section>
<section class="grid detail-grid"><section class="panel"><h2>Store identity, GPS &amp; KYC</h2><?php foreach([['Store / owner',($vendor['shop_name']??'—').' / '.($vendor['owner_name']??$vendor['name'])],['Mobile / email',($vendor['mobile']?:'—').' / '.($vendor['email']?:'—')],['GPS / geofence',($vendor['latitude']??'—').', '.($vendor['longitude']??'—').' · '.($vendor['proximity_radius_m']??'—').' m'],['Address',($vendor['address']?:'—')],['GSTIN / KYC',($vendor['gstin']??'—').' / '.($vendor['kyc_status']??'PENDING')]] as $r):?><div class="kv"><span><?=e($r[0])?></span><strong><?=e($r[1])?></strong></div><?php endforeach?><div class="kv"><span>Documents</span><strong><?php foreach(['logo_path'=>'Store logo','identity_proof_path'=>'ID proof · Verified','address_proof_path'=>'Address proof · Match','gst_document_path'=>'GST certificate · GSTIN match','cancelled_cheque_path'=>'Cancelled cheque · Bank match'] as $f=>$label):?><?php if(!empty($vendor[$f])&& (can('vendors.kyc.approve')||can('vendors.manage'))):?><a class="btn small secondary" target="_blank" rel="noopener" href="<?=e($vendor[$f])?>"><?=e($label)?></a><?php endif?> <?php endforeach?></strong></div></section><section class="panel"><h2>Settlement banking &amp; proofs</h2><?php foreach([['Account holder',$vendor['bank_account_holder']?:'—'],['Account number',mask_account($vendor['bank_account_number']??null)],['IFSC / UPI',($vendor['bank_ifsc']?:'—').' / '.($vendor['settlement_upi']?:'—')],['Schedule / bank status',($vendor['settlement_cycle']?:'—').' / '.($vendor['bank_verification_status']??'PENDING')]] as $r):?><div class="kv"><span><?=e($r[0])?></span><strong><?=e($r[1])?></strong></div><?php endforeach?><p class="help">Bank details are read-only here; use the verification/change workflow to modify them.</p></section></section>
<section class="panel"><div class="panel-head"><h2>Commission &amp; account profile</h2><span class="help">Sensitive banking fields cannot be edited here</span></div><?php if(can('vendors.manage')):?><form method="post" class="grid form-grid"><?=csrf_field()?><input type="hidden" name="action" value="SAVE_PROFILE"><label>Commission rate (%)<input name="commission_rate" type="number" min="0" max="100" step="0.01" value="<?=e($vendor['commission_rate'])?>"></label><label>Commission rule<input name="commission_rule" value="<?=e($vendor['commission_rule']??'')?>"></label><label class="full">Internal onboarding notes<textarea name="onboarding_notes"><?=e($vendor['onboarding_notes']??'')?></textarea></label><div class="full"><button class="btn">Save vendor profile</button></div></form><?php endif?></section>
<section class="panel"><div class="panel-head"><h2>Complete order, claim &amp; payout ledger</h2><span class="help">Immutable source records · <?=e(count($ledger))?> shown</span></div><div class="table-wrap"><table><thead><tr><th>ID</th><th>Date &amp; time</th><th>Activity / source</th><th>Bill</th><th>Discount</th><th>Commission</th><th>Net payout</th><th>Status</th></tr></thead><tbody><?php foreach($ledger as $r):?><tr><td><?=e($r['id'])?></td><td><?=e($r['event_date'])?></td><td><?=e($r['source'])?></td><td><?=money($r['gross'])?></td><td><?=money($r['discount'])?></td><td><?=money($r['commission'])?></td><td><?=money($r['net'])?></td><td><span class="badge <?=strtolower(e($r['status']))?>"><?=e($r['status'])?></span></td></tr><?php endforeach?></tbody></table><?php if(!$ledger):?><div class="empty">No vendor ledger records.</div><?php endif?></div></section>
<section class="panel"><div class="panel-head"><h2>Admin audit history</h2><span class="help">Immutable actions for this vendor</span></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Action</th><th>Admin</th><th>Reason / change</th><th>IP</th></tr></thead><tbody><?php foreach($audits as $a):?><tr><td><?=e($a['created_at'])?></td><td><?=e($a['action'])?></td><td><?=e($a['admin_id']??'System')?></td><td><?=e((string)($a['new_data']??'—'))?></td><td><?=e($a['ip_address']??'—')?></td></tr><?php endforeach?></tbody></table><?php if(!$audits):?><div class="empty">No audit entries yet.</div><?php endif?></div></section>
<?php if(can('vendors.manage')):?><dialog id="control"><form method="post" class="stack"><?=csrf_field()?><h2>Vendor account controls</h2><label>Action<select name="action"><option value="ACTIVATE">Activate outlet</option><option value="SUSPEND">Suspend / freeze outlet</option><option value="CLOSE">Deactivate account (soft close)</option></select></label><label>Reason (required)<textarea name="reason" required></textarea></label><div class="actions"><button class="btn secondary" type="button" onclick="control.close()">Cancel</button><button class="btn danger">Confirm action</button></div></form></dialog><?php endif?><?php require APP_ROOT.'/includes/footer.php';
